<template><view class="page"><view class="title">门店日常任务</view><picker v-if="stores.length" :range="stores" range-key="store_name" @change="change"><view class="store">{{ store?.store_name||'请选择门店' }} ▾</view></picker><view class="tabs"><view v-for="p in periods" :key="p.key" :class="{active:mode===p.key}" @click="mode=p.key;load()">{{ p.label }}</view></view><view class="hint">{{ range.from }} 至 {{ range.to }} · 全店共享进度</view><view v-if="loading" class="empty">正在加载…</view><view v-if="error" class="error">{{ error }}<button @click="load">重试</button></view><view v-if="!loading&&!error&&!rows.length" class="empty">当前门店在这个周期暂无下发任务</view><view v-for="row in rows" :key="row.id" class="card" @click="uni.navigateTo({url:'/pages/tasks/detail?id='+row.id})"><view class="top"><text>{{ row.title }}</text><text :class="['state',row.status]">{{ taskStatus(row.status) }}</text></view><view class="hint">{{ row.store_name }} · {{ row.business_date }}</view><view class="hint">进行中 {{ row.in_progress??Math.max(0,(row.total||0)-(row.completed||0)) }} · 已完成 {{ row.completed||0 }}/{{ row.total||0 }}</view><view class="bottom">{{ row.contributors }} 人参与 <text>查看任务 →</text></view></view><view v-if="rows.length>=1000" class="hint">结果较多，请缩小日期或门店范围。</view></view></template>
<script setup>
import {ref,computed} from 'vue'
import {onShow,onHide,onUnload,onPullDownRefresh} from '@dcloudio/uni-app'
import api from '../../common/api'
import {activeStore,selectStore,taskRange,taskStatus} from '../../common/task-context'
const stores=ref([]),store=ref(null),mode=ref('day'),rows=ref([]),loading=ref(false),error=ref(''),periods=[{key:'day',label:'本日'},{key:'week',label:'本周'},{key:'month',label:'本月'}],range=computed(()=>taskRange(mode.value))
let timer,sequence=0
function stop(){clearInterval(timer);sequence++}
onHide(stop);onUnload(stop)
async function load(){if(!store.value)return;const request=++sequence;loading.value=true;error.value='';try{const result=await api.taskList({...range.value,store_id:store.value.id});if(request===sequence)rows.value=result.rows}catch(e){rows.value=[];error.value=e.message}finally{loading.value=false;uni.stopPullDownRefresh()}}
function change(e){store.value=stores.value[Number(e.detail.value)];selectStore(store.value);load()}
onShow(async()=>{stop();timer=setInterval(()=>{if(!loading.value)load()},10000);try{const config=await api.taskConfig();stores.value=config.stores;store.value=stores.value.find(s=>s.id===activeStore()?.id)||stores.value[0]||null;if(store.value)selectStore(store.value);await load()}catch(e){error.value=e.message}})
onPullDownRefresh(load)
</script>
<style scoped>.page{padding:32rpx}.title{font-size:40rpx;font-weight:700}.store{margin:24rpx 0;font-size:29rpx}.tabs{display:flex;background:#fff;border-radius:18rpx;margin-bottom:20rpx;padding:8rpx}.tabs view{flex:1;text-align:center;padding:18rpx}.tabs .active{background:#fff1e9;color:#d94f2b;border-radius:14rpx;font-weight:600}.hint{font-size:25rpx;color:#8b949c;line-height:1.7}.card{margin-top:24rpx;padding:28rpx;background:#fff;border-radius:22rpx}.top,.bottom{display:flex;justify-content:space-between;align-items:center}.top{font-size:30rpx;font-weight:600;margin-bottom:16rpx}.state{font-size:24rpx;color:#6b7781;font-weight:400}.approved{color:#278351}.pending{color:#be7b15}.rejected,.error{color:#c34530}.bottom{margin-top:24rpx;padding-top:20rpx;border-top:1px solid #f1f2f4;font-size:25rpx;color:#7a848d}.bottom text{color:#d94f2b}.empty{padding:90rpx 20rpx;text-align:center;color:#89939b}</style>
