<template><view class="page"><view class="identity"><view class="avatar">{{ (user.display_name||user.username||'我').slice(0,1) }}</view><view class="name">{{ user.display_name||user.username }}</view><view class="muted">{{ user.position_name||'未配置岗位' }}</view></view><view class="card"><view class="row">账号 <text>{{ user.username }}</text></view><view class="row">岗位 <text>{{ user.position_name||'未配置' }}</text></view><view class="row">当前门店 <text>{{ store?.store_name||'未选择' }}</text></view></view><view class="card"><view class="title">个人信息</view><view class="muted">可编辑显示姓名和联系电话，岗位与门店由有权限的人员调整。</view><view class="label">显示姓名</view><input v-model="form.display_name" maxlength="40" placeholder="请输入姓名"/><view class="label">联系电话</view><input v-model="form.phone" maxlength="30" placeholder="请输入联系电话"/><button :loading="busy" :disabled="busy" class="primary" @click="save">保存个人信息</button></view><button class="logout" @click="logout">退出登录</button><view v-if="error" class="error">{{ error }}</view></view></template>
<script setup>
import {ref,reactive} from 'vue'
import {onShow} from '@dcloudio/uni-app'
import api from '../../common/api'
import {getToken,saveSession,clearAllSession} from '../../common/request'
import {activeStore} from '../../common/task-context'
const user=ref({}),store=ref(null),busy=ref(false),error=ref(''),form=reactive({display_name:'',phone:''})
onShow(async()=>{if(!getToken())return uni.reLaunch({url:'/pages/login/login'});store.value=activeStore();try{user.value=(await api.me()).user;form.display_name=user.value.display_name||'';form.phone=user.value.phone||''}catch(e){error.value=e.message}})
async function save(){busy.value=true;error.value='';try{user.value=(await api.updateProfile({...form})).user;saveSession(getToken(),user.value);uni.showToast({title:'已保存'})}catch(e){error.value=e.message}finally{busy.value=false}}
function logout(){uni.showModal({title:'退出登录',content:'退出后可重新使用微信或账号登录。',success:r=>{if(r.confirm){clearAllSession();uni.removeStorageSync('mp_active_store');uni.reLaunch({url:'/pages/login/login'})}}})}
</script>
<style scoped>.page{padding:32rpx}.identity{text-align:center;padding:40rpx 0}.avatar{width:100rpx;height:100rpx;line-height:100rpx;border-radius:30rpx;background:#d94f2b;color:#fff;font-size:46rpx;margin:0 auto 20rpx}.name{font-size:38rpx;font-weight:700}.muted{color:#8b949c;font-size:25rpx;line-height:1.7}.card{padding:30rpx;border-radius:24rpx;background:#fff;margin-bottom:24rpx}.row{display:flex;justify-content:space-between;padding:22rpx 0;font-size:27rpx}.row text{color:#6d7780;max-width:70%;text-align:right}.title{font-weight:700;font-size:30rpx}.label{font-size:26rpx;margin:24rpx 0 12rpx}input{background:#f5f6f8;padding:22rpx;border-radius:14rpx}.primary{background:#d94f2b;color:#fff;margin-top:30rpx;font-size:28rpx}.logout{color:#d94f2b;background:#fff;font-size:28rpx}.error{color:#ba3e30;padding:20rpx}</style>
