<template>
  <div class="mapping-page"><AnalysisPerspectiveNav /><AnalysisSectionNav />
    <section class="mapping-hero"><div><span>PRODUCT MAPPING</span><h2>{{ scopeLabel }} · 菜品关联</h2><p>将第三方平台商品绑定到堂食标准菜品库，建立统一成本与统计口径。</p></div></section>
    <section class="mapping-summary"><div><span>平台商品</span><b>{{ data.totals.total_products||0 }}</b></div><div><span>已关联</span><b>{{ data.totals.mapped||0 }}</b></div><div><span>待关联</span><b>{{ (data.totals.total_products||0)-(data.totals.mapped||0) }}</b></div></section>
    <section class="mapping-panel" v-loading="loading"><header><div><h3>平台商品绑定</h3><p>同一平台商品绑定一次后，所有门店销售数据共用该标准菜品成本。</p></div><el-input v-model="keyword" clearable placeholder="搜索平台商品" /></header>
      <el-table :data="filteredProducts" height="570"><el-table-column prop="platform" label="平台" width="125"/><el-table-column prop="product_name" label="平台商品名称" min-width="210"/>
        <el-table-column label="累计销量" width="100" align="right"><template #default="{row}">{{ Number(row.quantity||0).toLocaleString('zh-CN') }}</template></el-table-column>
        <el-table-column label="绑定标准菜品" min-width="300"><template #default="{row}"><el-select v-model="row.menu_item_id" filterable placeholder="选择堂食标准菜品" style="width:100%"><el-option v-for="menu in data.menu_items" :key="menu.id" :label="menuLabel(menu)" :value="menu.id" /></el-select></template></el-table-column>
        <el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.menu_item_id?'success':'warning'" size="small">{{ row.menu_item_id?'已关联':'待关联' }}</el-tag></template></el-table-column>
        <el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-button link type="primary" :loading="savingId===`${row.platform}|${row.product_name}`" @click="save(row)">保存</el-button></template></el-table-column>
      </el-table><el-empty v-if="!loading&&!data.products.length" description="暂无平台商品，请先导入商品销售数据" /></section>
  </div>
</template>
<script setup>
import {computed,onMounted,reactive,ref,watch} from 'vue';import {useRoute} from 'vue-router';import {ElMessage} from 'element-plus';import {getBusinessProductMappings,saveBusinessProductMapping} from '@/api';import AnalysisPerspectiveNav from './AnalysisPerspectiveNav.vue';import AnalysisSectionNav from './AnalysisSectionNav.vue'
const route=useRoute(),loading=ref(false),savingId=ref(''),keyword=ref(''),data=reactive({products:[],menu_items:[],totals:{}});const scope=computed(()=>({group:'overview','group-buy':'group-buy',delivery:'delivery'})[route.params.perspective]||'overview');const scopeLabel=computed(()=>({overview:'集团总视角','group-buy':'团购视角',delivery:'外卖视角'})[scope.value]);const filteredProducts=computed(()=>data.products.filter(r=>!keyword.value||`${r.platform}${r.product_name}`.includes(keyword.value)));const menuLabel=m=>`${m.name} · ${[m.spec_unit,m.spec_weight].filter(Boolean).join('/')||'标准'} · ¥${Number(m.cost||0).toFixed(2)}`
async function load(){loading.value=true;try{Object.assign(data,await getBusinessProductMappings(scope.value))}catch(e){ElMessage.error(e.message)}finally{loading.value=false}}
async function save(row){if(!row.menu_item_id)return ElMessage.warning('请选择标准菜品');savingId.value=`${row.platform}|${row.product_name}`;try{await saveBusinessProductMapping({scope:scope.value,platform:row.platform,external_product_name:row.product_name,menu_item_id:row.menu_item_id});row.mapped=true;ElMessage.success('菜品关联已保存')}catch(e){ElMessage.error(e.message)}finally{savingId.value=''}}watch(()=>route.params.perspective,load);onMounted(load)
</script>
<style scoped>
.mapping-page{color:#172033}.mapping-hero{margin-bottom:13px;padding:24px 27px;border-radius:17px;color:#fff;background:linear-gradient(125deg,#253158,#7a5bc7)}.mapping-hero span{font-size:9px;letter-spacing:.16em;opacity:.7}.mapping-hero h2{margin:6px 0;font-size:23px}.mapping-hero p{margin:0;font-size:11px;opacity:.76}.mapping-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:13px}.mapping-summary div,.mapping-panel{border:1px solid #e5e9f0;border-radius:13px;background:#fff}.mapping-summary div{padding:15px}.mapping-summary span,.mapping-summary b{display:block}.mapping-summary span{color:#8b95a6;font-size:10px}.mapping-summary b{margin-top:7px;font-size:20px}.mapping-panel{overflow:hidden}.mapping-panel header{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-bottom:1px solid #edf0f4}.mapping-panel h3{margin:0;font-size:14px}.mapping-panel p{margin:4px 0 0;color:#929cad;font-size:9px}.mapping-panel header .el-input{width:260px}@media(max-width:680px){.mapping-summary{grid-template-columns:1fr}.mapping-panel header{align-items:stretch;flex-direction:column;gap:10px}.mapping-panel header .el-input{width:100%}}
</style>
