<template>
<section class="studio">
<header class="studio-bar"><div class="project"><el-icon><Document /></el-icon><select aria-label="任务项目" :value="editor.id||''" @change="switchProject"><option value="">新表单草稿</option><option v-for="t in templates" :key="t.id" :value="t.id">{{ t.title }} · v{{ t.version }}</option></select></div><div class="studio-tabs"><button :class="{active:mode==='edit'}" @click="mode='edit'">编辑</button><button :class="{active:mode==='settings'}" @click="mode='settings'">设置</button></div><div class="actions"><el-button @click="blank">新建表单</el-button><el-button @click="openPreview">填写预览</el-button><el-button type="primary" :loading="busy" @click="save">保存项目</el-button></div></header>
<div class="context"><span>门店自动关联，无需填写</span><span>拖动排序 · 题号自动从 01 开始</span><span>保存后选择门店下发</span></div>
<div v-show="mode==='settings'" class="settings"><h2>全局设置</h2><section><h3>全部题目必填设置</h3><p>批量调整后，仍可在单题属性里单独设置。</p><el-button @click="allRequired(true)">全部必填</el-button><el-button @click="allRequired(false)">全部选填</el-button></section><section><h3>执行方式</h3><p>全店共享一份进度。单人完成：任意成员填写一次，其他成员查看；多人共同完成：允许成员补充同一项。批量设置后可以逐题调整。</p><el-button @click="allExecution('single')">全部设为单人完成</el-button><el-button @click="allExecution('shared')">全部设为多人共同完成</el-button></section><section><h3>版本与生效范围</h3><p>已下发任务保留原版。保存修改后，在「下发到门店」选定执行日期与门店。</p></section><el-button @click="mode='edit'">返回编辑</el-button></div>
<div v-show="mode==='edit'" class="search-bar"><el-input v-model="search" clearable aria-label="搜索题型" placeholder="搜索题型或常用题目" style="width:250px"/><span>点击或拖动题型添加题目，点击题目配置填写规则</span></div>
<FcDesigner v-show="mode==='edit'" ref="designer" :menu="menu" :config="config" height="750px" @preview-submit="previewSubmitted" @active="preserveInstructions"><template #header><div class="paper-heading"><el-input v-model="editor.title" aria-label="项目名称" maxlength="100" placeholder="请输入表单标题" class="title"/><el-input v-model="editor.description" aria-label="填写说明" type="textarea" :rows="2" maxlength="1000" placeholder="请输入表单描述或检查标准" class="description"/></div></template></FcDesigner>
<footer>题型、填写要求和审核记录沿用门店任务权限 <span>本地测试 · 未上云</span></footer>
<el-dialog v-model="previewOpen" title="填写预览 · 不保存任务数据" width="min(800px,94vw)" class="task-form-preview"><h2>{{ editor.title }}</h2><p>{{ editor.description }}</p><FormPreview v-if="previewOpen" :rule="previewRules" :option="previewOptions" @submit="previewSubmitted" /></el-dialog>
</section>
</template>
<script setup>
import {ref,computed,watch,nextTick,defineComponent,h,onMounted,onBeforeUnmount} from 'vue'
import {Document} from '@element-plus/icons-vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import FcDesigner from '@form-create/designer'
import {toDesignerRule,fromDesignerRules} from '@/utils/store-task-form-schema.mjs'
import StoreTaskInstructions from './StoreTaskInstructions.vue'
import StoreTaskInstructionEditor from './StoreTaskInstructionEditor.vue'
const props=defineProps({editor:{type:Object,required:true},templates:{type:Array,default:()=>[]},busy:Boolean}),emit=defineEmits(['edit','new','save'])
const designer=ref(null),mode=ref('edit'),search=ref(''),previewOpen=ref(false),previewRules=ref([])
const FormPreview=FcDesigner.formCreate.$form(),previewOptions={form:{labelPosition:'top',labelWidth:'auto'},submitBtn:{innerText:'验证填写'},resetBtn:false}
function openPreview(){try{previewRules.value=fromDesignerRules(designer.value.getRule()).map(toDesignerRule);previewOpen.value=true}catch(e){ElMessage.error(e.message)}}
const PhotoField=defineComponent({props:{min:{default:1},max:{default:1},modelValue:Array},emits:['update:modelValue'],setup(p,{emit}){return()=>h('div',{class:'task-photo'},[h('label',{class:'photo-upload'},[h('span','＋ 上传图片'),h('input',{type:'file',accept:'image/jpeg,image/png,image/webp',multiple:p.max>1,onChange:e=>{const files=[...e.target.files];if(files.length>p.max)return ElMessage.warning(`最多选择${p.max}张`);emit('update:modelValue',files.map(f=>f.name))}})]),h('small',p.min===p.max?`数量要求：正好 ${p.max} 张`:`最少 ${p.min} 张，最多 ${p.max} 张`),h('div',(p.modelValue||[]).join('、'))])}})
FcDesigner.component('taskPhoto',PhotoField)
FcDesigner.component('TaskInstructions',StoreTaskInstructions)
FcDesigner.component('TaskGuideEditor',StoreTaskInstructionEditor)
const OptionField=defineComponent({props:{modelValue:Array},emits:['update:modelValue'],setup(p,{emit}){const update=(i,v)=>{const a=(p.modelValue||[]).map(o=>({...o}));a[i]={label:v,value:v};emit('update:modelValue',a)};return()=>h('div',{class:'task-options'},[...(p.modelValue||[]).map((o,i)=>h('div',{class:'option-row'},[h('span',String(i+1)),h('input',{value:o.label,'aria-label':`选项 ${i+1}`,maxlength:80,onInput:e=>update(i,e.target.value)}),h('button',{type:'button',disabled:p.modelValue.length<=2,'aria-label':`删除选项 ${i+1}`,onClick:()=>emit('update:modelValue',p.modelValue.filter((_,j)=>j!==i))},'×')])),h('button',{type:'button',disabled:(p.modelValue||[]).length>=12,onClick:()=>emit('update:modelValue',[...(p.modelValue||[]),{label:'新选项',value:'新选项'}])},'＋ 添加选项')])}})
FcDesigner.component('TaskOptions',OptionField)
const labels={text:'填空题',choice:'单选题',multiple:'多选题',dropdown:'下拉选择',number:'数字',date:'日期',photo:'图片题'},icons={text:'icon-input',choice:'icon-radio',multiple:'icon-checkbox',dropdown:'icon-select',number:'icon-number',date:'icon-date',photo:'icon-upload'}
const optionEditor={type:'TaskOptions',field:'formCreateOptions',title:'选项内容',props:{column:[{label:'选项内容',key:'label'}],keyValue:'label'}}
function definition(type,name=`task_${type}`,label=labels[type],extra={}){return {name,label,icon:icons[type],input:true,style:false,event:false,validate:false,rule(){const r=toDesignerRule({id:crypto.randomUUID(),title:label,type,required:true,options:['已完成','未完成'],min:1,max:1,multiline:false,maxLength:2000,precision:2});r._fc_drag_tag=name;Object.assign(r.props,extra);return r},props(){const req={type:'switch',field:'formCreate$required',title:'此题必填'};if(type==='photo')return [req,{type:'inputNumber',field:'min',title:'最少上传（张）',props:{min:0,max:9}},{type:'inputNumber',field:'max',title:'最多上传（张）',props:{min:1,max:9}}];if(['choice','multiple','dropdown'].includes(type))return [req,optionEditor];if(type==='text')return [req,{type:'select',field:'type',title:'填写区域',options:[{label:'单行填空',value:'text'},{label:'多行文字',value:'textarea'}]},{type:'input',field:'placeholder',title:'填写提示'},{type:'inputNumber',field:'maxlength',title:'最多字数',props:{min:1,max:2000}},{type:'select',field:'format',title:'内容格式',options:[{label:'普通文字',value:'plain'},{label:'11位手机号',value:'phone'}]}];if(type==='number')return [req,{type:'inputNumber',field:'min',title:'最小数值',props:{controls:false}},{type:'inputNumber',field:'max',title:'最大数值',props:{controls:false}},{type:'inputNumber',field:'precision',title:'小数位数',props:{min:0,max:6}},{type:'input',field:'placeholder',title:'填写提示'}];return [req]}}}
const definitions=[...Object.keys(labels).map(t=>definition(t)),definition('text','task_name','姓名',{maxlength:50,placeholder:'请填写姓名'}),definition('text','task_phone','手机号',{maxlength:11,format:'phone',placeholder:'请输入11位手机号'}),definition('text','task_note','异常说明',{type:'textarea',placeholder:'说明异常及处理措施'}),definition('number','task_amount','金额',{min:0,precision:2,placeholder:'单位：元'})]
const baseMenu=[{name:'basic',title:'基础题型',list:definitions.slice(0,7)},{name:'common',title:'常用题目',list:definitions.slice(7)}]
const menu=computed(()=>baseMenu.map(group=>({...group,list:group.list.filter(item=>item.label.includes(search.value.trim()))})))
const config={showMenuBar:false,showAi:false,showLanguage:false,showJsonPreview:false,showCustomProps:false,showEventForm:false,showStyleForm:false,showFormConfig:false,showValidateForm:false,showComponentName:false,showControl:false,showInputData:false,showDevice:true,showPreviewBtn:false,fieldReadonly:true,autoActive:true,switchType:[Object.keys(labels).map(t=>`task_${t}`)],baseRule:{append:false,rule:()=>[{type:'input',field:'title',title:'问题标题',props:{maxlength:100}},{type:'select',field:'formCreateExecution_mode',title:'执行方式',options:[{label:'单人完成（任意成员完成一次）',value:'single'},{label:'多人共同完成（允许共同补充）',value:'shared'}]},{type:'TaskGuideEditor',field:'formCreatePrefix',title:'题目说明（文字与图片）'}]},formOptions:{form:{labelPosition:'top',labelWidth:'auto',size:'default'},submitBtn:{innerText:'验证填写',show:true},resetBtn:false}}
let baseline='',ready=false,activeQuestion=null
function preserveInstructions(rule){if(activeQuestion?.field===rule.field&&activeQuestion.type!==rule.type&&activeQuestion.prefix)rule.prefix=JSON.parse(JSON.stringify(activeQuestion.prefix));if(activeQuestion?.field===rule.field&&activeQuestion.type!==rule.type)rule.execution_mode=activeQuestion.execution_mode||'shared';activeQuestion=rule}
const serialize=()=>JSON.stringify({title:props.editor.title,description:props.editor.description,rules:designer.value?.getRule().map(r=>({type:r.type,field:r.field,title:r.title,info:r.info,prefix:r.prefix,execution_mode:r.execution_mode,required:r.$required,props:r.props,options:r.options}))})
const dirty=()=>ready&&serialize()!==baseline
async function load(){activeQuestion=null;await nextTick();if(!designer.value)return;designer.value.addComponent(definitions);designer.value.setRule((props.editor.questions||[]).map(toDesignerRule));await nextTick();baseline=serialize();ready=true}
watch(()=>props.editor.questions,load,{immediate:true})
async function discard(){if(!dirty())return true;try{await ElMessageBox.confirm('当前有未保存的修改，是否放弃？','切换表单',{confirmButtonText:'放弃修改',cancelButtonText:'继续编辑',type:'warning'});return true}catch{return false}}
defineExpose({discard})
async function switchProject(e){const id=e.target.value;e.target.value=String(props.editor.id||'');if(!await discard())return;const t=props.templates.find(t=>String(t.id)===id);if(t)emit('edit',t);else blank(false)}
async function blank(ask=true){if(ask&&!await discard())return;emit('new',{title:'',description:'',questions:[]});mode.value='edit'}
function save(){try{const questions=fromDesignerRules(designer.value.getRule());if(!props.editor.title.trim())throw new Error('请填写表单标题');props.editor.questions=questions;emit('save')}catch(e){ElMessage.error(e.message)}}
function allExecution(mode){const rules=designer.value.getRule();rules.forEach(q=>q.execution_mode=mode);designer.value.setRule(rules);designer.value.addOperationRecord();ElMessage.success('已批量设置执行方式')}
function allRequired(required){const r=designer.value.getRule();r.forEach(q=>q.$required=required);designer.value.setRule(r);designer.value.addOperationRecord();ElMessage.success(required?'已全部设为必填':'已全部设为选填')}
function previewSubmitted(){ElMessage.success('填写校验通过，预览数据不会保存为门店任务')}
function beforeUnload(e){if(dirty()){e.preventDefault();e.returnValue=''}}
onMounted(()=>{load();window.addEventListener('beforeunload',beforeUnload)})
onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload))
</script>
<style scoped>
.search-bar{display:flex;gap:16px;align-items:center;padding:12px 18px;background:#fff;border-bottom:1px solid #edf0f6}.search-bar>span{font-size:12px;color:#8490a3}:deep(.task-options){display:grid;gap:10px}:deep(.option-row){display:flex;align-items:center;gap:6px}:deep(.option-row input){width:100%;min-width:0;padding:8px;border:1px solid #dce3ef;border-radius:4px;font:inherit}:deep(.task-options button){border:1px solid #dce3ef;background:#fff;padding:6px;border-radius:4px;color:#2864e8;cursor:pointer}:deep(.task-options button:disabled){opacity:.4;cursor:default}
.studio{background:#fff;border:1px solid #e5eaf2;border-radius:10px;overflow:hidden;color:#20304b}.studio-bar{padding:14px 18px;display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap;border-bottom:1px solid #edf0f6}.project,.actions{display:flex;align-items:center;gap:10px}.project>.el-icon{color:#2764e8;font-size:24px}.project select{border:0;font-weight:600;font-size:14px;background:transparent;color:inherit;max-width:230px;min-height:36px;cursor:pointer}.studio-tabs{display:flex;gap:24px}.studio-tabs button{border:0;background:none;min-height:40px;border-bottom:2px solid transparent;font-size:14px;cursor:pointer;color:#78879e}.studio-tabs button.active{color:#2864e8;border-bottom-color:#2864e8}.actions .el-button{margin:0}.context{display:flex;justify-content:space-between;padding:12px 20px;background:#f9fbfe;color:#718096;font-size:12px}.paper-heading{padding:30px;border-bottom:1px solid #edf0f6;background:#fff}.title :deep(.el-input__wrapper){box-shadow:none;background:transparent}.title :deep(input){font-size:25px;font-weight:650;text-align:center;color:#20304b}.description{margin-top:12px}.description :deep(textarea){box-shadow:none;background:transparent;resize:none;text-align:center;font-size:13px;color:#8290a5}footer{padding:12px 20px;color:#8a96a9;font-size:11px;border-top:1px solid #edf0f6;display:flex;justify-content:space-between}.settings{padding:30px;max-width:760px;margin:auto;min-height:500px}.settings h2{font-size:21px}.settings section{padding:22px 0;border-bottom:1px solid #edf0f6}.settings h3{font-size:15px}.settings p{font-size:13px;color:#75849c;line-height:1.8}.settings>.el-button{margin-top:24px}
:deep(._fc-r-tab-props > ._fd-config-item){display:none}:deep(._fc-l){width:215px!important;background:#fff}:deep(._fc-r){width:300px!important;background:#fff}:deep(._fc-r-tab-props){overflow-x:hidden}:deep(._fc-r .el-form-item__content){min-width:0}:deep(._fc-m){background:#f4f6fa}:deep(._fc-m-drag){height:auto!important;overflow:visible!important;max-width:760px;margin:24px auto!important;background:#fff;border-radius:8px;box-shadow:0 4px 24px #20304b08}:deep(._fc-m-drag ._fd-draggable-drag){height:auto!important;overflow:visible!important}:deep(._fc-m-drag ._fd-drag-tool){padding:22px 20px;border-bottom:1px solid #eff2f7}:deep(._fc-m-drag ._fd-drag-tool.active){border-left:3px solid #2864e8;background:#fbfdff}:deep(._fc-l ._fc-menu-item){border:1px solid #e4e9f0;border-radius:6px;margin:4px;min-height:38px;background:#fff}:deep(._fc-l ._fc-menu-item:hover){border-color:#2864e8;background:#f5f8ff}:deep(._fc-m-drag .el-form){counter-reset:task-question}:deep(._fc-m-drag ._fd-drag-tool .el-form-item__label){counter-increment:task-question}:deep(._fc-m-drag ._fd-drag-tool .el-form-item__label .fc-form-title)::before{content:counter(task-question,decimal-leading-zero) '. ';color:#738299;margin-right:6px}:deep(.task-photo){display:grid;gap:8px;width:100%}:deep(.photo-upload){display:flex;height:80px;border:1px dashed #ccd7e8;background:#f8fafe;align-items:center;justify-content:center;border-radius:6px;color:#6280ad;position:relative}:deep(.photo-upload input){position:absolute;inset:0;opacity:0;width:100%;cursor:pointer}:deep(.task-photo small){color:#8490a3;font-size:12px}:deep(._fc-m .el-form-item__label){font-size:15px;font-weight:600}:deep(._fc-r .el-form-item__label){font-size:13px}
@media(max-width:1100px){:deep(._fc-l){width:160px!important}:deep(._fc-r){width:235px!important}.context span:nth-child(2){display:none}}@media(max-width:780px){.studio-bar{padding:12px}.studio-tabs{order:3;width:100%}.context span:last-child{display:none}:deep(._fc-l){width:130px!important}:deep(._fc-r){width:200px!important}footer span{display:none}}
</style>

<style>.task-form-preview .el-form{counter-reset:preview-question}.task-form-preview .el-form-item__label{counter-increment:preview-question}.task-form-preview .fc-form-title::before{content:counter(preview-question,decimal-leading-zero) ". ";margin-right:6px;color:#78879e}</style>
