const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),express=require('express'),initSqlJs=require('sql.js');
const permissions=require('../lib/permissions'),notifications=require('../lib/notifications');
test('所有角色默认开放消息，前后端一致且通知规则仍须授权',async()=>{
 const source=fs.readFileSync('frontend/src/permissions.js','utf8');const frontend=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
 for(const roles of [[],['payroll.prepare'],['staff.view'],['notifications.view'],['*']]){assert(permissions.can(roles,'notifications.view'));assert(frontend.permits(roles,'notifications.view'));assert(frontend.permits(roles,['notifications.view']));assert.equal(permissions.can(roles,'notifications.rules'),roles.includes('*'));assert.equal(frontend.permits(roles,'notifications.rules'),roles.includes('*'))}
 const app=express();app.use((req,res,next)=>{if(req.headers['x-user'])req.user={id:Number(req.headers['x-user'])};next()});app.use(permissions.createGuard({getUserById:id=>id===1?{permissions_json:'[]'}:null,hasFullAccess:()=>false}));for(const path of ['/api/notifications','/api/notifications/create','/api/notifications/recipients','/api/notifications/settings'])app.all(path,(req,res)=>res.json({ok:true}));
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const url=`http://127.0.0.1:${server.address().port}`;
 try{for(const path of ['/api/notifications','/api/notifications/create','/api/notifications/recipients'])assert.equal((await fetch(url+path,{headers:{'x-user':'1'}})).status,200);assert.equal((await fetch(url+'/api/notifications/settings',{headers:{'x-user':'1'}})).status,403);assert.equal((await fetch(url+'/api/notifications')).status,401);assert.equal((await fetch(url+'/api/notifications',{headers:{'x-user':'99'}})).status,401)}finally{server.closeAllConnections();await new Promise(r=>server.close(r))}
});
test('普通角色可选择收件人、发送和接收，第三方不能读取或处理他人通知',async()=>{
 const SQL=await initSqlJs(),raw=new SQL.Database();const db={run:(s,p=[])=>raw.run(s,p),queryAll:(s,p=[])=>{const q=raw.prepare(s);q.bind(p);const rows=[];while(q.step())rows.push(q.getAsObject());q.free();return rows},save:()=>{}};db.queryOne=(s,p)=>db.queryAll(s,p)[0]||null;db.insert=(s,p)=>{db.run(s,p);return db.queryOne('SELECT last_insert_rowid() id').id};
 raw.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY,username TEXT,display_name TEXT,password_hash TEXT,phone TEXT,permissions_json TEXT,role TEXT DEFAULT '普通岗位');INSERT INTO users(id,username,display_name,password_hash,phone,permissions_json) VALUES(1,'sender','发送者','secret','private','[]'),(2,'receiver','接收者','secret','private','[]'),(3,'other','其他人','secret','private','[]');CREATE TABLE notifications(id INTEGER PRIMARY KEY,type TEXT,kind TEXT,title TEXT,content TEXT,dedupe_key TEXT,related_employee_id INTEGER,payload_json TEXT,created_by INTEGER,source TEXT,publish_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE notification_recipients(id INTEGER PRIMARY KEY,notification_id INTEGER,user_id INTEGER,status TEXT DEFAULT '待处理',later_at TEXT DEFAULT '',archived_at TEXT DEFAULT '',popup_at TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(notification_id,user_id));`);
 const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={id:Number(req.headers['x-user'])};next()});app.use(permissions.createGuard({getUserById:id=>db.queryOne('SELECT * FROM users WHERE id=?',[id]),hasFullAccess:()=>false}));
 const source=fs.readFileSync('server.js','utf8');for(const prefix of ["app.get('/api/notifications/recipients',","app.post('/api/notifications/create',","app.get('/api/notifications',","app.put('/api/notifications/:id',"]){const a=source.indexOf(prefix),b=source.indexOf('\n});',a)+5;new Function('app','db','notifications','notificationCheck',source.slice(a,b))(app,db,notifications,()=>({generated:0}))}
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const call=async(id,path,method='GET',body)=>{const r=await fetch(`http://127.0.0.1:${server.address().port}${path}`,{method,headers:{'x-user':String(id),'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()}};
 try{const contacts=await call(1,'/api/notifications/recipients');assert.equal(contacts.status,200);assert.equal(contacts.data.users.length,3);assert.deepEqual(Object.keys(contacts.data.users[0]).sort(),['display_name','id','role','username']);const sent=await call(1,'/api/notifications/create','POST',{title:'测试通知',content:'测试内容',user_ids:[2]});assert.equal(sent.status,200);const mine=await call(2,'/api/notifications');assert.equal(mine.data.notifications.length,1);assert.equal(mine.data.notifications[0].title,'测试通知');assert.equal((await call(3,'/api/notifications')).data.notifications.length,0);assert.equal((await call(3,'/api/notifications/'+sent.data.notification_id,'PUT',{action:'confirm'})).status,404);assert.equal((await call(2,'/api/notifications/'+sent.data.notification_id,'PUT',{action:'confirm'})).status,200)}finally{server.closeAllConnections();await new Promise(r=>server.close(r));raw.close()}
});

