<template>
  <div class="payslips" v-loading="loading">
    <section class="card-compact"><h2>员工工资条查询</h2><p>按员工合并同月各门店工资，查看本店及支援门店承担明细。</p><div class="filters"><label>工资月份</label><el-date-picker v-model="period" type="month" value-format="YYYY-MM" :clearable="false" @change="load" /><el-select v-model="view" @change="load" style="width:240px"><el-option label="已提交（含待审核）" value="submitted" /><el-option label="仅已审核" value="approved" /><el-option v-if="canViewUnsubmitted" label="全部工资表（含未提交预览）" value="all" /></el-select><el-input v-model="search" placeholder="查询员工姓名 / 员工编号" clearable style="width:240px" /><el-button @click="load">刷新</el-button></div><p>待审核、草稿及退回金额均为预览；存在未纳入门店时，当前合计不代表完整月工资。查询基于工资表快照，尚未制作的工资不会自动估算。</p></section>
    <section class="card-compact"><el-table :data="filtered" border empty-text="当前月份和范围暂无员工工资记录"><el-table-column type="index" label="序号" width="65" /><el-table-column prop="employee_id" label="员工编号" width="100" /><el-table-column prop="name" label="姓名" min-width="100" /><el-table-column label="承担门店" min-width="210"><template #default="{row}">{{ row.contributions.map(c=>c.store_name).join('、') }}</template></el-table-column><el-table-column label="应发合计" width="125"><template #default="{row}">{{ money(row.totals.gross_salary) }}</template></el-table-column><el-table-column label="代扣合计" width="125"><template #default="{row}">{{ money(row.totals.deductions) }}</template></el-table-column><el-table-column label="实发合计" width="125"><template #default="{row}">{{ money(row.totals.net_salary) }}</template></el-table-column><el-table-column label="汇总状态" width="180"><template #default="{row}"><el-tag :type="row.all_approved?'success':'warning'">{{ row.all_approved?'已审核汇总':row.complete?'未全部审核 · 预览':'门店数据未齐' }}</el-tag></template></el-table-column><el-table-column label="操作" width="95"><template #default="{row}"><el-button link type="primary" @click="selectedId=row.employee_id">查看工资条</el-button></template></el-table-column></el-table></section>
    <section v-if="selected" class="card-compact"><h3>{{ selected.name }} · {{ period }} 工资条</h3><p>员工编号 {{ selected.employee_id }} · {{ selected.position || '职务未登记' }}</p><el-alert v-if="!selected.all_approved" :title="!selected.complete?'部分门店尚未纳入，当前工资汇总不完整':'当前工资尚未全部审核，仅供核对'" type="warning" :closable="false" /><div class="totals"><div>应发合计<b>{{ money(selected.totals.gross_salary) }}</b></div><div>代扣合计<b>{{ money(selected.totals.deductions) }}</b></div><div>实发合计<b>{{ money(selected.totals.net_salary) }}</b></div></div><h4>门店工资覆盖情况</h4><el-table :data="selected.coverage" size="small"><el-table-column prop="store_name" label="门店 / 集团" min-width="220" /><el-table-column prop="status" label="工资表状态" width="170" /><el-table-column label="是否计入当前汇总" width="170"><template #default="{row}">{{ row.included?'已计入':'未计入' }}</template></el-table-column></el-table><h4>各门店承担明细</h4><el-table :data="selected.contributions" border><el-table-column prop="store_name" label="门店 / 集团" min-width="200" fixed /><el-table-column prop="status" label="状态" width="100" /><el-table-column label="工资归集" min-width="170"><template #default="{row}">{{ row.is_dispatch_support?'支援门店承担':'原归属门店承担' }}<small v-if="row.dispatch_origin_store_name">原店：{{ row.dispatch_origin_store_name }}</small></template></el-table-column><el-table-column prop="actual_days" label="计薪天数" width="100" /><el-table-column prop="dispatch_out_days" label="派出天数" width="100" /><el-table-column prop="support_days" label="支援天数" width="100" /><el-table-column v-for="column in moneyColumns" :key="column.key" :label="column.label" width="120"><template #default="{row}">{{ money(row[column.key]) }}</template></el-table-column><el-table-column label="支援日期" min-width="220"><template #default="{row}">{{ row.dispatch_dates.join('、') || '—' }}</template></el-table-column></el-table><p>标准月工资不跨店重复相加。各店金额沿用工资表计算结果，合计按各店显示金额累加。</p></section>
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { getEmployeePayslips } from '@/api'
const today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit'}).format(new Date()),[y,m]=today.split('-').map(Number)
const period=ref(new Date(Date.UTC(y,m-2,1)).toISOString().slice(0,7)),view=ref('submitted'),search=ref(''),loading=ref(false),employees=ref([]),selectedId=ref(null),canViewUnsubmitted=ref(false)
const filtered=computed(()=>employees.value.filter(row=>`${row.name} ${row.employee_id}`.includes(search.value.trim())))
const selected=computed(()=>employees.value.find(row=>row.employee_id===selectedId.value))
const money=value=>'￥'+Number(value || 0).toFixed(2)
const moneyColumns=[{key:'actual_base_salary',label:'基本工资份额'},{key:'actual_position_allowance',label:'岗位补贴份额'},{key:'actual_performance_salary',label:'绩效工资份额'},{key:'actual_attendance_bonus',label:'全勤奖份额'},{key:'actual_housing_allowance',label:'房补份额'},{key:'weekday_overtime_pay',label:'工作日加班'},{key:'restday_overtime_pay',label:'休息日加班'},{key:'part_time_salary',label:'兼职工资'},{key:'reward',label:'奖励'},{key:'penalty',label:'罚款'},{key:'late_early_deduction',label:'迟到早退'},{key:'other_deduction',label:'其他扣款'},{key:'gross_salary',label:'应发工资'},{key:'social_insurance',label:'社保'},{key:'income_tax',label:'个税'},{key:'utilities_fee',label:'水电'},{key:'uniform_deposit',label:'工衣押金'},{key:'deductions',label:'代扣合计'},{key:'net_salary',label:'实发工资'}]
let requestId=0
async function load(){const token=++requestId;selectedId.value=null;loading.value=true;try{const data=await getEmployeePayslips(period.value,view.value);if(token===requestId){employees.value=data.employees;canViewUnsubmitted.value=data.can_view_unsubmitted}}catch(error){if(token===requestId){employees.value=[];ElMessage.error(error.message)}}finally{if(token===requestId)loading.value=false}}
onMounted(load)
</script>
<style scoped>
.payslips{display:grid;gap:16px;min-width:0}.payslips>section{min-width:0;max-width:100%;overflow:hidden}.payslips h2,.payslips h3{margin-top:0}.payslips p{font-size:13px;line-height:1.7;color:#64748b}.filters{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.filters :deep(.el-date-editor){width:150px}.totals{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:16px}.totals>div{background:#f5f8fc;border-radius:8px;padding:18px;color:#64748b}.totals b{display:block;margin-top:8px;color:#234e7c;font-size:22px}.payslips small{display:block;color:#64748b}@media(max-width:650px){.totals{grid-template-columns:1fr}}
</style>
