<template>
  <div class="payroll-workbench">
    <section class="payroll-hero"><div><span class="eyebrow">人事专区 · 工资表制作</span><h2>月度工资工作台</h2><p>自动生成员工与薪酬快照，再录入当月出勤、加班、奖罚和扣缴，保存后可继续编辑或导出。</p></div><div class="sheet-count"><b>{{ savedSheets.length }}</b><span>已保存工资表</span></div></section>
    <section class="payroll-controls card-compact"><el-form inline class="sheet-form"><el-form-item label="门店"><el-select v-model="form.store_name" filterable placeholder="选择门店" style="width:250px"><el-option v-for="store in stores" :key="store.id" :label="store.store_name" :value="store.store_name" /></el-select></el-form-item><el-form-item label="工资月份"><el-date-picker v-model="form.period" type="month" value-format="YYYY-MM" style="width:150px" /></el-form-item><el-form-item label="应出勤天数"><el-input-number v-model="form.scheduled_days" :min="1" :max="31" controls-position="right" style="width:120px" /></el-form-item><el-button type="primary" :loading="preparing" @click="prepareSheet">生成 / 打开</el-button></el-form><span class="control-note">相同门店和月份会打开已保存工资表，不覆盖历史数据。</span></section>
    <section v-if="sheet" class="payroll-sheet card-compact"><header class="sheet-header"><div><h3>{{ sheet.store_name }} · {{ sheet.period }} 工资表</h3><p>共 {{ sheet.items.length }} 人 · {{ sheet.status || '草稿' }} · 最后更新 {{ sheet.updated_at || '刚刚' }}</p></div><div class="sheet-actions"><el-button :loading="saving" @click="saveSheet">保存明细</el-button><el-button type="success" :disabled="!sheet.id" @click="downloadSheet">导出 Excel</el-button></div></header><div class="summary-grid"><div><small>员工数</small><b>{{ sheet.items.length }}</b></div><div><small>应发工资</small><b>¥{{ summary.gross.toFixed(2) }}</b></div><div><small>代扣合计</small><b class="deduct">¥{{ summary.deductions.toFixed(2) }}</b></div><div><small>实发工资</small><b class="net">¥{{ summary.net.toFixed(2) }}</b></div></div>
      <div class="sheet-scroll"><el-table :data="sheet.items" border size="small" row-key="id" class="payroll-table">
        <el-table-column label="#" width="52" fixed><template #default="{ $index }">{{ $index + 1 }}</template></el-table-column><el-table-column prop="name" label="姓名" width="100" fixed /><el-table-column prop="position" label="职务" width="92" /><el-table-column prop="entry_date" label="入职日期" width="104" />
        <el-table-column label="出勤"><el-table-column v-for="column in attendanceColumns" :key="column.key" :label="column.label" width="106"><template #default="{ row }"><el-input-number v-model="row[column.key]" :min="0" controls-position="right" size="small" class="cell-number" /></template></el-table-column><el-table-column label="实际出勤" width="90"><template #default="{ row }">{{ actualDays(row) }}</template></el-table-column></el-table-column>
        <el-table-column label="标准工资"><el-table-column v-for="column in salaryColumns" :key="column.key" :label="column.label" width="118"><template #default="{ row }"><el-input-number v-model="row[column.key]" :min="0" controls-position="right" size="small" class="cell-number" /></template></el-table-column><el-table-column label="标准工资" width="110"><template #default="{ row }">¥{{ standardSalary(row).toFixed(2) }}</template></el-table-column></el-table-column>
        <el-table-column label="实际出勤工资"><el-table-column label="基本工资" width="112"><template #default="{ row }">¥{{ actualComponent(row,'base_salary').toFixed(2) }}</template></el-table-column><el-table-column label="工作日加班" width="112"><template #default="{ row }">¥{{ weekdayOvertimePay(row).toFixed(2) }}</template></el-table-column><el-table-column label="休息日加班" width="112"><template #default="{ row }">¥{{ restdayOvertimePay(row).toFixed(2) }}</template></el-table-column><el-table-column label="岗位补贴" width="108"><template #default="{ row }">¥{{ actualComponent(row,'position_allowance').toFixed(2) }}</template></el-table-column><el-table-column label="绩效工资" width="108"><template #default="{ row }">¥{{ actualComponent(row,'performance_salary').toFixed(2) }}</template></el-table-column><el-table-column label="全勤奖" width="104"><template #default="{ row }">¥{{ actualComponent(row,'attendance_bonus').toFixed(2) }}</template></el-table-column><el-table-column label="房补" width="104"><template #default="{ row }">¥{{ actualComponent(row,'housing_allowance').toFixed(2) }}</template></el-table-column></el-table-column>
        <el-table-column label="兼职工资"><el-table-column label="小时数" width="100"><template #default="{ row }"><el-input-number v-model="row.part_time_hours" :min="0" controls-position="right" size="small" class="cell-number" /></template></el-table-column><el-table-column label="统一工价" width="110"><template #default="{ row }"><el-input-number v-model="row.part_time_hourly_rate" :min="0" controls-position="right" size="small" class="cell-number" /></template></el-table-column><el-table-column label="兼职工资" width="110"><template #default="{ row }">¥{{ (n(row.part_time_hours)*n(row.part_time_hourly_rate)).toFixed(2) }}</template></el-table-column></el-table-column>
        <el-table-column label="奖罚"><el-table-column v-for="column in monthlyColumns.slice(0,4)" :key="column.key" :label="column.label" width="110"><template #default="{ row }"><el-input-number v-model="row[column.key]" :min="0" controls-position="right" size="small" class="cell-number" /></template></el-table-column></el-table-column><el-table-column label="应发工资" width="118"><template #default="{ row }"><b class="gross">¥{{ grossSalary(row).toFixed(2) }}</b></template></el-table-column>
        <el-table-column label="代扣代缴"><el-table-column v-for="column in monthlyColumns.slice(4)" :key="column.key" :label="column.label" width="110"><template #default="{ row }"><el-input-number v-model="row[column.key]" :min="0" controls-position="right" size="small" class="cell-number" /></template></el-table-column></el-table-column><el-table-column label="实发工资" width="118"><template #default="{ row }"><b class="net">¥{{ netSalary(row).toFixed(2) }}</b></template></el-table-column><el-table-column label="银行卡信息"><el-table-column prop="bank_card_number" label="银行卡号" width="178" /><el-table-column prop="bank_name" label="开户行" width="170" /><el-table-column prop="id_card_number" label="身份证号" width="190" /><el-table-column prop="phone" label="手机号" width="130" /></el-table-column>
      </el-table></div><p class="sheet-footnote">字段与财务工资表一致：固定薪酬来自生成时的 C 级档案快照；当月出勤、加班、奖罚和扣缴只保存在本月工资表内，不会反写员工档案。</p></section>
    <section v-else class="empty-sheet card-compact"><h3>选择门店和工资月份开始制作</h3><p>系统会生成可编辑预览，不会直接下载文件，也不会覆盖已有工资表。</p></section>
    <section v-if="savedSheets.length" class="saved-sheet-list card-compact"><div class="card-header">已保存的工资表</div><el-table :data="savedSheets" size="small"><el-table-column prop="period" label="月份" width="110" /><el-table-column prop="store_name" label="门店" min-width="240" /><el-table-column prop="employee_count" label="员工数" width="85" /><el-table-column prop="status" label="状态" width="90" /><el-table-column prop="updated_at" label="最后更新" width="170" /><el-table-column label="操作" width="80"><template #default="{ row }"><el-button link type="primary" @click="loadSavedSheet(row.id)">打开</el-button></template></el-table-column></el-table></section>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { exportPayrollSheet, getPayrollSheet, getPayrollSheets, getStores, preparePayrollSheet, savePayrollSheet } from '@/api'
const stores=ref([]),savedSheets=ref([]),sheet=ref(null),preparing=ref(false),saving=ref(false)
const form=reactive({store_name:'',period:new Date().toISOString().slice(0,7),scheduled_days:26})
const attendanceColumns=[{key:'scheduled_days',label:'应出勤'},{key:'personal_leave',label:'事假'},{key:'sick_leave',label:'病假'},{key:'join_leave',label:'入/离职缺勤'},{key:'support_days',label:'跨店支援'},{key:'annual_leave',label:'年假'},{key:'weekday_overtime_hours',label:'工作日加班时长'},{key:'restday_overtime_hours',label:'休息日加班时长'}]
const salaryColumns=[{key:'base_salary',label:'基本工资'},{key:'position_allowance',label:'岗位补贴'},{key:'performance_salary',label:'绩效工资'},{key:'attendance_bonus',label:'全勤奖'},{key:'housing_allowance',label:'房补'}]
const monthlyColumns=[{key:'reward',label:'奖励'},{key:'penalty',label:'罚款'},{key:'late_early_deduction',label:'迟到早退'},{key:'other_deduction',label:'其他扣款'},{key:'social_insurance',label:'社保'},{key:'income_tax',label:'个税'},{key:'utilities_fee',label:'水电'},{key:'uniform_deposit',label:'工衣押金'}]
const n=v=>Math.max(0,Number(v)||0)
const actualDays=r=>Math.max(0,n(r.scheduled_days)-n(r.personal_leave)-n(r.sick_leave)-n(r.join_leave)+n(r.support_days)+n(r.annual_leave))
const standardSalary=r=>r.hire_type==='兼职'?n(r.part_time_hourly_rate):['base_salary','position_allowance','performance_salary','attendance_bonus','housing_allowance'].reduce((s,k)=>s+n(r[k]),0)
const actualComponent=(r,key)=>r.hire_type==='兼职'?0:n(r[key])*actualDays(r)/Math.max(1,n(r.scheduled_days))
const weekdayOvertimePay=r=>n(r.weekday_overtime_hours)*n(r.weekday_overtime_rate)
const restdayOvertimePay=r=>n(r.restday_overtime_hours)*n(r.restday_overtime_rate)
const grossSalary=r=>['base_salary','position_allowance','performance_salary','attendance_bonus','housing_allowance'].reduce((s,k)=>s+actualComponent(r,k),0)+weekdayOvertimePay(r)+restdayOvertimePay(r)+n(r.part_time_hours)*n(r.part_time_hourly_rate)+n(r.reward)-n(r.penalty)-n(r.late_early_deduction)-n(r.other_deduction)
const deductions=r=>['social_insurance','income_tax','utilities_fee','uniform_deposit'].reduce((s,k)=>s+n(r[k]),0)
const netSalary=r=>grossSalary(r)-deductions(r)
const summary=computed(()=> (sheet.value?.items||[]).reduce((o,r)=>({gross:o.gross+grossSalary(r),deductions:o.deductions+deductions(r),net:o.net+netSalary(r)}),{gross:0,deductions:0,net:0}))
async function loadLists(){try{const[a,b]=await Promise.all([getStores({page:1,page_size:500}),getPayrollSheets()]);stores.value=a.stores||[];savedSheets.value=b.sheets||[]}catch(e){ElMessage.error('工资表资料读取失败：'+e.message)}}
async function prepareSheet(){if(!form.store_name||!form.period){ElMessage.warning('请选择门店和工资月份');return}preparing.value=true;try{sheet.value=(await preparePayrollSheet(form)).sheet;await loadLists();ElMessage.success('工资表预览已生成')}catch(e){ElMessage.error('生成失败：'+e.message)}finally{preparing.value=false}}
async function loadSavedSheet(id){try{sheet.value=(await getPayrollSheet(id)).sheet;Object.assign(form,{store_name:sheet.value.store_name,period:sheet.value.period,scheduled_days:sheet.value.scheduled_days})}catch(e){ElMessage.error('打开失败：'+e.message)}}
async function saveSheet(){if(!sheet.value)return;saving.value=true;try{sheet.value=(await savePayrollSheet(sheet.value.id,{scheduled_days:form.scheduled_days,items:sheet.value.items})).sheet;form.scheduled_days=sheet.value.scheduled_days;await loadLists();ElMessage.success('工资表明细已保存')}catch(e){ElMessage.error('保存失败：'+e.message)}finally{saving.value=false}}
async function downloadSheet(){try{const blob=await exportPayrollSheet(sheet.value.id),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=`${sheet.value.store_name}-${sheet.value.period}工资表.xlsx`;a.click();URL.revokeObjectURL(href)}catch(e){ElMessage.error('导出失败：'+e.message)}}
onMounted(loadLists)
</script>

<style scoped>
.payroll-workbench{display:grid;gap:14px;min-width:0;max-width:100%;overflow:hidden}.payroll-workbench>section{min-width:0;max-width:100%}.payroll-hero{display:flex;justify-content:space-between;align-items:center;padding:22px 26px;border:1px solid #d9e7f8;border-radius:16px;background:linear-gradient(120deg,#f9fcff,#f3f8ff)}.eyebrow{color:#5278ae;font-size:12px;font-weight:700}.payroll-hero h2{margin:5px 0 6px;color:#24466f;font-size:22px}.payroll-hero p,.control-note,.sheet-header p,.sheet-footnote,.empty-sheet p{margin:0;color:#8291a7;font-size:12px;line-height:1.6}.sheet-count{display:grid;min-width:105px;padding:11px 16px;border-radius:12px;background:#fff;text-align:center;box-shadow:0 5px 16px rgba(43,83,132,.08)}.sheet-count b{color:#2860b8;font-size:24px}.sheet-count span{color:#8091a8;font-size:11px}.payroll-controls{display:flex;justify-content:space-between;align-items:center;gap:12px}.sheet-form{display:flex;flex-wrap:wrap;align-items:center;gap:4px;min-width:0}.sheet-form :deep(.el-form-item){margin:0}.control-note{white-space:nowrap}.sheet-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.sheet-header h3{margin:0 0 5px;color:#274a73;font-size:16px}.sheet-actions{display:flex;gap:8px}.summary-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:14px;overflow:hidden;border:1px solid #e0e9f5;border-radius:12px}.summary-grid>div{display:grid;gap:5px;padding:12px 16px;border-right:1px solid #e7edf6}.summary-grid>div:last-child{border:0;background:#f2fbf7}.summary-grid small{color:#8392a7;font-size:12px}.summary-grid b{color:#315d93;font-size:18px}.deduct{color:#bd6a27!important}.net{color:#118067!important}.gross{color:#315d93}.sheet-scroll{width:100%;min-width:0;max-width:100%;overflow-x:auto;overflow-y:hidden;overscroll-behavior-x:contain;border:1px solid #e6edf6;border-radius:10px;scrollbar-gutter:stable}.payroll-table{width:2720px!important;min-width:2720px}.cell-number{width:100%}.sheet-footnote{margin:12px 3px 0}.empty-sheet{text-align:center;padding:48px}.empty-sheet h3{margin:0 0 8px;color:#4a6583;font-size:16px}.saved-sheet-list{padding-bottom:12px}@media(max-width:900px){.payroll-hero,.payroll-controls,.sheet-header{align-items:flex-start;flex-direction:column}.control-note{white-space:normal}.summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.summary-grid>div:nth-child(2){border-right:0}.summary-grid>div:nth-child(-n+2){border-bottom:1px solid #e7edf6}}
</style>
