<template>
  <div class="roster-page">
    <section class="card-compact">
      <div class="toolbar"><h2>员工周排班</h2><span v-if="context.own_only">{{ context.scopes[0]?.label }}</span><template v-else><el-radio-group v-model="scopeType" @change="changeScope"><el-radio-button value="store">门店员工</el-radio-button><el-radio-button value="office">办公室员工</el-radio-button></el-radio-group><StoreRegionSelect v-if="scopeType==='store'" v-model="storeId" :stores="stores" :clearable="false" input-width="240px" @update:model-value="changeScope" /></template><el-button @click="moveWeek(-7)">上一周</el-button><el-date-picker v-model="pickedDate" type="date" value-format="YYYY-MM-DD" :clearable="false" style="width:155px" @change="changeWeek" /><el-button @click="moveWeek(7)">下一周</el-button></div>
      <div class="toolbar"><span>{{ week.week_start }} 至 {{ week.dates?.[6] }}</span><el-tag :type="week.status==='published'?'success':'info'">{{ week.status==='published'?'正式员工本周已固定':'排班草稿' }}</el-tag><el-tag v-if="dirty" type="warning">排班有未保存修改</el-tag><span class="legend work">正常出勤</span><span class="legend rest">正常休息</span><span class="legend leave">请假</span><span class="legend overtime">加班存假</span><el-button v-if="week.can_submit" :loading="saving" @click="save(false)">保存</el-button><el-button v-if="week.can_submit && week.status!=='published'" type="primary" :loading="saving" @click="save(true)">提交并固定本周</el-button></div>
      <p class="hint">点击日期安排班次，点击员工姓名查看个人假期库存。办公室工作 / 休息沿用人事统一月历。正式员工按周固定，兼职可调整未来班次；支援员工由所属门店排班。</p>
      <div class="roster-scroll" v-loading="loading"><table class="roster-table"><thead><tr><th>员工</th><th v-for="date in week.dates" :key="date">{{ date.slice(5) }}<small>{{ weekdays[new Date(date+'T12:00:00+08:00').getUTCDay()] }}</small></th></tr></thead><tbody><tr v-for="person in week.employees" :key="person.employee_id"><th><button class="employee-name" @click="openBalance(person)">{{ person.name }}</button><small>{{ person.hire_type }}</small></th><td v-for="day in person.days" :key="day.date"><button :aria-label="`${person.name} ${day.date} ${label(day)}`" :class="['shift-cell',color(day)]" @click="openDay(person,day)"><b>{{ label(day) }}</b><small v-if="day.start_time">{{ day.start_time }}–{{ day.end_time }}{{ day.next_day?' 次日':'' }}</small><small v-if="day.actual?.hours!==null && day.actual?.hours!==undefined">实际 {{ day.actual.hours }} 小时</small><small v-if="day.actual?.banked">存假 +{{ day.actual.banked }} 天</small><small v-if="day.actual?.used">调休 {{ day.actual.used }} 天</small><small v-if="day.type==='leave' && day.exception.decision!=='leave'">请假待确认</small></button></td></tr><tr v-if="!week.employees?.length"><td colspan="8" class="empty">本周暂无本店归属员工</td></tr></tbody></table></div>
      <p class="hint">实际考勤按已结束日期核算；不足休息额度且存假不足时，须人事确认请假，否则核实后按旷工处理。缺卡保持待核。</p>
    </section>
    <el-dialog v-model="dayVisible" :title="`${selectedPerson?.name || ''} · ${selectedDay?.date || ''}`" width="520px">
      <template v-if="selectedDay"><el-form label-width="110px"><el-form-item label="排班安排"><el-radio-group v-model="dayForm.type" :disabled="!selectedDay.can_edit"><el-radio-button value="work" :disabled="!selectedDay.can_edit || scope==='office' && selectedDay.office_type!=='work'">正常出勤</el-radio-button><el-radio-button :value="scope==='office' && selectedDay.office_type==='holiday'?'holiday':'rest'" :disabled="!selectedDay.can_edit || scope==='office' && !['rest','holiday'].includes(selectedDay.office_type)">正常休息</el-radio-button><el-radio-button value="leave">请假</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="['work','overtime'].includes(dayForm.type)" label="班次时间"><el-input v-model="dayForm.start_time" :disabled="!selectedDay.can_edit" placeholder="上班 HH:mm" style="width:125px" /><span> — </span><el-input v-model="dayForm.end_time" :disabled="!selectedDay.can_edit" placeholder="下班 HH:mm" style="width:125px" /><el-checkbox v-model="dayForm.next_day" :disabled="!selectedDay.can_edit">次日</el-checkbox></el-form-item><el-form-item label="排班 / 请假原因"><el-input v-model="dayForm.reason" type="textarea" :disabled="!selectedDay.can_edit" maxlength="500" /></el-form-item></el-form><el-checkbox v-if="selectedDay.can_edit && selectedPerson.hire_type==='兼职' && ['work','overtime'].includes(dayForm.type)" v-model="copyTimes">同步本周其余出勤班次的时间</el-checkbox><el-button v-if="selectedDay.can_edit" type="primary" @click="applyDay">应用到排班草稿</el-button>
        <el-divider>考勤确认与请假申请</el-divider><p class="hint">{{ selectedDay.actual?.note || '工时以打卡为准。审批和工时修订由人事处理。' }}</p><el-form label-width="110px"><el-form-item v-if="week.can_confirm" label="人事认定"><el-select v-model="exceptionForm.decision"><el-option label="待核 / 申请请假" value="pending" /><el-option label="批准请假" value="leave" /><el-option label="确认旷工" value="absent" /><el-option label="确认实际出勤" value="work" /></el-select></el-form-item><el-form-item v-if="week.can_confirm" label="核实工时"><el-input v-model="exceptionForm.hours" inputmode="decimal" placeholder="选填；留空使用完整打卡工时" /></el-form-item><el-form-item label="原因 / 核实依据"><el-input v-model="exceptionForm.reason" type="textarea" maxlength="500" /></el-form-item></el-form><el-button :loading="saving" @click="saveException">{{ week.can_confirm?'保存人事认定':'提交请假 / 待核申请' }}</el-button>
      </template>
    </el-dialog>
    <el-dialog v-model="balanceVisible" :title="`${balancePerson?.name || ''} · 假期库存`" width="min(850px,96vw)">
      <div v-loading="balanceLoading"><el-alert v-if="balanceError" :title="balanceError" type="error" :closable="false" /><template v-if="account"><div class="balance-summary"><div><small>个人存假可用</small><b>{{ account.balance }} 天</b></div><div><small>本月正常休息剩余</small><b>{{ normalRestRemaining }} 天</b></div><div><small>本月已使用存假</small><b>{{ currentMonth?.used || 0 }} 天</b></div></div><p class="hint">截至 {{ account.as_of }}；{{ account.active_from }} 起启用库存。先用本月正常休息额度，再扣最早到期的存假。每笔三个月有效，12 月 31 日结束清空。{{ account.employee.hire_type==='兼职'?'兼职按实际工时计薪，暂不存假。':'' }}</p><h4>存假批次</h4><el-table :data="account.lots" size="small" max-height="200" empty-text="暂无存假"><el-table-column prop="date" label="产生日期" /><el-table-column prop="amount" label="存入天数" /><el-table-column prop="remaining" label="剩余天数" /><el-table-column label="到期日（当日不可用）"><template #default="{row}"><span :class="{'expiring':row.remaining>0 && row.expires_on<=soon}">{{ row.expires_on }}{{ row.remaining>0 && row.expires_on<=soon?' · 即将到期':'' }}</span></template></el-table-column></el-table><h4>库存流水</h4><el-table :data="[...account.events].reverse()" size="small" max-height="220" empty-text="暂无流水"><el-table-column prop="date" label="日期" /><el-table-column label="类型"><template #default="{row}">{{ eventLabels[row.type] }}</template></el-table-column><el-table-column label="天数"><template #default="{row}">{{ row.type==='earn'?'+':'−' }}{{ row.amount }}</template></el-table-column><el-table-column prop="source_date" label="存假来源日期" /></el-table><el-collapse><el-collapse-item title="核算修订记录"><el-table :data="revisions" size="small"><el-table-column prop="version" label="版本" /><el-table-column prop="source" label="原因" /><el-table-column prop="created_at" label="时间" /></el-table></el-collapse-item></el-collapse></template></div>
    </el-dialog>
  </div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import StoreRegionSelect from '@/components/StoreRegionSelect.vue'
import {getRosterContext,getRosterWeek,saveRosterWeek,getRosterBalance,saveRosterException} from '@/api'
const context=ref({scopes:[],own_only:false}),scope=ref(''),scopeType=ref('store'),storeId=ref(null),pickedDate=ref(''),week=ref({employees:[],dates:[]}),loading=ref(false),saving=ref(false)
const copyTimes=ref(false),baseline=ref('')
const planSnapshot=()=>JSON.stringify((week.value.employees || []).map(person=>({id:person.employee_id,days:person.days.map(day=>Object.fromEntries(['date','type','start_time','end_time','next_day','reason'].map(key=>[key,day[key]])))})))
const dirty=computed(()=>!!baseline.value && planSnapshot()!==baseline.value)
const dayVisible=ref(false),selectedPerson=ref(null),selectedDay=ref(null),dayForm=reactive({}),exceptionForm=reactive({})
const balanceVisible=ref(false),balanceLoading=ref(false),balancePerson=ref(null),account=ref(null),revisions=ref([]),balanceError=ref('')
const weekdays=['周日','周一','周二','周三','周四','周五','周六'],eventLabels={earn:'超额出勤存假',use:'调休扣减',expire:'三个月到期清除',year_clear:'年底清零'}
const stores=computed(()=>context.value.scopes.filter(s=>s.value.startsWith('store:')).map(s=>({id:Number(s.value.split(':')[1]),store_name:s.label})))
const currentMonth=computed(()=>account.value?.months.find(m=>m.period===account.value.as_of.slice(0,7)))
const normalRestRemaining=computed(()=>Math.max(0,(currentMonth.value?.rest_allowance || 0)-(currentMonth.value?.normal_rest_used || 0)))
const add=(date,days)=>{const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
const monday=date=>add(date,-((new Date(date+'T00:00:00Z').getUTCDay()+6)%7))
const soon=computed(()=>account.value?add(account.value.as_of,7):'')
const color=day=>{const actual=day.actual?.status;if(day.exception.decision==='leave' && (!actual || actual==='planned'))return 'leave';if(actual && !['planned','pending'].includes(actual))return actual==='absent'?'leave':actual;return day.type==='holiday'?'rest':day.type==='overtime'?'overtime':day.type}
const label=day=>{const actual=day.actual?.status;if(day.exception.decision==='leave' && (!actual || actual==='planned'))return '请假';if(actual==='pending')return '考勤待核';if(actual==='absent')return '旷工';return {work:'正常出勤',rest:'正常休息',leave:'请假',overtime:'加班存假',holiday:'正常休息'}[actual==='planned' || !actual?day.type:actual] || '待核'}
let loadGeneration=0,balanceGeneration=0
async function load(){if(!scope.value || !pickedDate.value)return;const generation=++loadGeneration;loading.value=true;try{const data=await getRosterWeek({scope:scope.value,week_start:monday(pickedDate.value)});if(generation===loadGeneration){week.value=data.week;baseline.value=planSnapshot()}}catch(error){ElMessage.error(error.message)}finally{if(generation===loadGeneration)loading.value=false}}
function changeScope(){scope.value=scopeType.value==='office'?'office':storeId.value?`store:${storeId.value}`:'';load()}
function changeWeek(){pickedDate.value=monday(pickedDate.value);load()}
function moveWeek(days){pickedDate.value=add(pickedDate.value,days);load()}
function openDay(person,day){copyTimes.value=false;selectedPerson.value=person;selectedDay.value=day;Object.assign(dayForm,{type:day.type,start_time:day.start_time,end_time:day.end_time,next_day:day.next_day,reason:day.reason});Object.assign(exceptionForm,{decision:day.exception.decision,reason:day.exception.reason || day.reason || '',hours:day.exception.hours ?? ''});dayVisible.value=true}
function applyDay(){if(dayForm.type==='leave' && !dayForm.reason?.trim()){ElMessage.warning('请填写请假原因');return}Object.assign(selectedDay.value,dayForm);if(copyTimes.value)for(const day of selectedPerson.value.days)if(day.can_edit && ['work','overtime'].includes(day.type))Object.assign(day,{start_time:dayForm.start_time,end_time:dayForm.end_time,next_day:dayForm.next_day});dayVisible.value=false}
async function save(publish){try{let reason='';if(week.value.status==='published' && week.value.can_confirm){const answer=await ElMessageBox.prompt('请输入本次排班调整原因','调整已固定排班',{inputValidator:value=>!!value?.trim() || '请填写原因'});reason=answer.value}if(publish)await ElMessageBox.confirm('提交后正式员工本周排班固定，后续调整需由人事处理。','提交周排班');saving.value=true;week.value=(await saveRosterWeek({scope:scope.value,week_start:week.value.week_start,version:week.value.version,employees:week.value.employees,publish,reason})).week;baseline.value=planSnapshot();ElMessage.success('排班已保存')}catch(error){if(error!=='cancel' && error!=='close')ElMessage.error(error.message)}finally{saving.value=false}}
async function saveException(){if(dirty.value){ElMessage.warning('请先保存排班草稿，再提交考勤确认，避免丢失未保存班次');return}saving.value=true;try{await saveRosterException(selectedPerson.value.employee_id,selectedDay.value.date,{version:selectedDay.value.exception.version,decision:week.value.can_confirm?exceptionForm.decision:'pending',reason:exceptionForm.reason,hours:week.value.can_confirm && exceptionForm.hours!==''?Number(exceptionForm.hours):null});dayVisible.value=false;await load();ElMessage.success('已记录并重新核算库存')}catch(error){ElMessage.error(error.message)}finally{saving.value=false}}
async function openBalance(person){balanceVisible.value=true;balancePerson.value=person;account.value=null;balanceError.value='';balanceLoading.value=true;const generation=++balanceGeneration;try{const result=await getRosterBalance(person.employee_id);if(generation===balanceGeneration){account.value=result.account;revisions.value=result.revisions}}catch(error){if(generation===balanceGeneration)balanceError.value=error.message}finally{if(generation===balanceGeneration)balanceLoading.value=false}}
onMounted(async()=>{loading.value=true;try{context.value=await getRosterContext();pickedDate.value=monday(context.value.today);scope.value=context.value.scopes[0]?.value || '';scopeType.value=scope.value==='office'?'office':'store';storeId.value=scope.value.startsWith('store:')?Number(scope.value.split(':')[1]):null;await load()}catch(error){ElMessage.error(error.message)}finally{loading.value=false}})
</script>
<style scoped>
.roster-page{min-width:0}.toolbar{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:14px}.toolbar h2{margin:0;font-size:20px}.hint{font-size:12px;color:#64748b;line-height:1.6}.legend{padding:4px 9px;border:1px solid #e2e8f0;border-radius:5px;font-size:12px}.work{background:#e8f7ec}.rest{background:#fff}.leave{background:#feecec}.overtime{background:#fff7cf}.roster-scroll{overflow:auto}.roster-table{width:100%;min-width:980px;border-collapse:collapse;font-size:13px}.roster-table th,.roster-table td{border:1px solid #e2e8f0;padding:7px;text-align:center}.roster-table thead th{background:#f8fafc}.roster-table small{display:block;margin-top:5px;font-weight:400;font-size:11px;color:#64748b}.roster-table tbody th{width:130px;position:sticky;left:0;background:#fff;z-index:1}.employee-name{border:0;background:none;color:#2563eb;font-size:14px;cursor:pointer;padding:5px}.shift-cell{display:flex;flex-direction:column;justify-content:center;align-items:center;width:100%;min-height:78px;border:1px solid #e2e8f0;border-radius:6px;cursor:pointer;color:#334155;font-family:inherit}.shift-cell:hover{border-color:#409eff}.empty{padding:35px!important;color:#64748b}.balance-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.balance-summary>div{display:grid;gap:9px;padding:15px;background:#f5f8fc;border-radius:8px}.balance-summary small{color:#64748b}.balance-summary b{font-size:22px;color:#2563eb}.expiring{color:#b45309}@media(max-width:600px){.balance-summary{grid-template-columns:1fr}}
</style>
