<template><view class="page"><view class="welcome">门店工作 · 每一天</view><view class="hero"><view class="kicker">当前门店</view><picker v-if="stores.length" :range="stores" range-key="store_name" @change="change"><view class="store">{{ store?.store_name }} ▾</view></picker><view v-else class="store">{{ loading?'正在加载…':'暂未配置门店' }}</view><view class="hello">{{ user.display_name||user.username }}，今天也一起把工作做好。</view><view class="date">{{ today }}</view></view><view v-if="error" class="error">{{ error }}<button @click="load">重新加载</button></view><view class="section"><text>今日任务</text><text class="link" @click="tasks">查看全部 →</text></view><view class="stats"><view><text class="number">{{ pendingCount }}</text><text>待完成</text></view><view><text class="number">{{ reviewCount }}</text><text>待审核</text></view><view><text class="number">{{ approvedCount }}</text><text>已通过</text></view></view><view v-if="!rows.length" class="empty">{{ loading?'正在加载任务…':hasTasks?'今天暂无下发任务':'当前岗位未开放门店任务' }}</view><view v-for="row in rows.slice(0,3)" :key="row.id" class="task" @click="uni.navigateTo({url:'/pages/tasks/detail?id='+row.id})"><view><view class="task-title">{{ row.title }}</view><view class="muted">进行中 {{ row.in_progress||0 }} · 已完成 {{ row.completed||0 }}/{{ row.total||0 }} · {{ row.business_date }}</view></view><text class="link">{{ taskStatus(row.status) }} →</text></view><view class="section">常用入口</view><view class="shortcuts"><view @click="tasks">✓<text>任务进度</text></view><view @click="uni.switchTab({url:'/pages/reports/index'})">¥<text>门店报表</text></view><view @click="uni.switchTab({url:'/pages/workbench/index'})">▦<text>全部功能</text></view><view @click="uni.switchTab({url:'/pages/mine/index'})">○<text>我的账号</text></view></view></view></template>
<script setup>
import {ref,computed} from 'vue'
import {onShow,onPullDownRefresh} from '@dcloudio/uni-app'
import api from '../../common/api'
import {getToken} from '../../common/request'
import {localDate} from '../../common/format'
import {activeStore,selectStore,taskStatus} from '../../common/task-context'
const user=ref({}),stores=ref([]),store=ref(null),rows=ref([]),error=ref(''),loading=ref(false),today=ref(localDate())
const can=p=>(user.value.position_permissions||[]).some(v=>v==='*'||v===p)
const hasTasks=computed(()=>['store-tasks.execute','store-tasks.review','store-tasks.manage'].some(can))
const pendingCount=computed(()=>rows.value.filter(r=>['draft','rejected'].includes(r.status)).length),reviewCount=computed(()=>rows.value.filter(r=>r.status==='pending').length),approvedCount=computed(()=>rows.value.filter(r=>r.status==='approved').length)
function tasks(){if(hasTasks.value)uni.navigateTo({url:'/pages/tasks/list'});else uni.showToast({title:'当前岗位未开放门店任务',icon:'none'})}
async function load(){if(!getToken())return uni.reLaunch({url:'/pages/login/login'});loading.value=true;error.value='';today.value=localDate();try{user.value=(await api.me()).user;if(hasTasks.value)stores.value=(await api.taskConfig()).stores;else if(can('analysis.view'))stores.value=(await api.storeList()).stores;else if(can('bookkeeping.manage'))stores.value=(await api.bookkeepingOptions()).stores;else stores.value=[];store.value=stores.value.find(s=>s.id===activeStore()?.id)||stores.value[0]||null;if(store.value)selectStore(store.value);rows.value=hasTasks.value&&store.value?(await api.taskList({from:today.value,to:today.value,store_id:store.value.id})).rows:[]}catch(e){error.value=e.message;rows.value=[]}finally{loading.value=false;uni.stopPullDownRefresh()}}
function change(e){store.value=stores.value[Number(e.detail.value)];selectStore(store.value);load()}
onShow(load);onPullDownRefresh(load)
</script>
<style scoped>.page{padding:32rpx}.welcome{font-size:26rpx;color:#919a9f;margin-bottom:24rpx}.hero{padding:36rpx;background:linear-gradient(130deg,#c94425,#ed7442);border-radius:28rpx;color:#fff}.kicker{opacity:.75;font-size:24rpx}.store{font-size:39rpx;font-weight:700;line-height:1.5;margin:16rpx 0}.hello{font-size:25rpx;opacity:.85;line-height:1.7}.date{margin-top:30rpx;font-size:24rpx;opacity:.7}.section{display:flex;justify-content:space-between;margin:40rpx 0 22rpx;font-size:32rpx;font-weight:700}.link{font-size:24rpx;color:#d94f2b;font-weight:400}.stats{display:flex;background:#fff;border-radius:22rpx;padding:30rpx 10rpx}.stats view{flex:1;display:flex;flex-direction:column;align-items:center;font-size:24rpx;color:#90999f;gap:12rpx}.number{font-size:46rpx;color:#273139;font-weight:700}.empty{color:#919a9f;font-size:26rpx;text-align:center;padding:36rpx}.task{display:flex;justify-content:space-between;align-items:center;background:#fff;border-radius:20rpx;padding:26rpx;margin-top:18rpx}.task-title{font-size:30rpx;font-weight:600;margin-bottom:10rpx}.muted{color:#919a9f;font-size:23rpx}.shortcuts{display:flex;background:#fff;border-radius:22rpx;padding:32rpx 8rpx}.shortcuts view{flex:1;text-align:center;color:#d94f2b;font-size:40rpx}.shortcuts text{display:block;font-size:23rpx;color:#59656f;margin-top:16rpx}.error{color:#b33b28;padding:20rpx}</style>
