<template>
  <main class="store-tasks" v-loading="loading">
    <header class="page-header"><div><p class="eyebrow">门店运营 / 固定工作</p><h1>门店日常任务</h1><p>一店一份任务，成员共同执行，提交后审核；与临时协同事项分别管理。</p></div><el-button @click="load">刷新</el-button></header>
    <el-alert v-if="error" :title="error" type="error" :closable="false" show-icon class="space" />
    <el-tabs v-model="tab">
      <el-tab-pane v-if="can('store-tasks.manage')" label="项目与表单" name="templates">
        <StoreTaskTemplateList :templates="templates" :plans="plans" @edit="edit" @new="newProject({title:'',description:'',questions:[]})" @dispatch="openDispatch" @plans="plansOpen=true" />
      </el-tab-pane>
      <el-tab-pane v-if="can('store-tasks.manage')" label="下发到门店" name="dispatch">
        <StoreTaskTemplateList :templates="templates" :plans="plans" @edit="edit" @new="newProject({title:'',description:'',questions:[]})" @dispatch="openDispatch" @plans="plansOpen=true" />
      </el-tab-pane>
      <el-tab-pane label="执行与审核" name="progress" lazy><el-radio-group v-model="progressView" class="space"><el-radio-button value="submissions">提交记录</el-radio-button><el-radio-button value="tasks">任务进度</el-radio-button></el-radio-group><StoreTaskSubmissionReview v-if="progressView==='submissions'" ref="submissionView" :stores="config.stores" :can-review="can('store-tasks.review')" /><template v-else>
        <div class="filters"><el-date-picker v-model="range" type="daterange" value-format="YYYY-MM-DD" :clearable="false" /><el-select v-model="storeId" clearable filterable placeholder="全部授权门店"><el-option v-for="s in config.stores" :key="s.id" :value="s.id" :label="s.store_name" /></el-select><el-button @click="loadRows">查询</el-button></div>
        <div class="metrics"><div v-for="s in ['draft','pending','approved','rejected']" :key="s"><span>{{ status(s) }}</span><strong>{{ rows.filter(r=>r.status===s).length }}</strong></div></div>
        <el-table :data="rows" stripe><el-table-column prop="store_name" label="门店" min-width="180" /><el-table-column prop="title" label="任务" min-width="140" /><el-table-column prop="business_date" label="业务日期" width="120" /><el-table-column label="状态" width="130"><template #default="{row}"><el-tag :type="tone(row.status)">{{ status(row.status) }}</el-tag></template></el-table-column><el-table-column label="门店共同进度" min-width="170"><template #default="{row}">进行中 {{row.in_progress}} · 已完成 {{row.completed}} / {{row.total}}</template></el-table-column><el-table-column prop="contributors" label="参与人数" width="100" /><el-table-column label="截止时间" min-width="170"><template #default="{row}">{{ fmt(row.due_at) }}<el-tag v-if="new Date(row.due_at)<new Date() && ['draft','rejected'].includes(row.status)" type="warning" size="small">逾期</el-tag></template></el-table-column><el-table-column label="操作" width="130"><template #default="{row}"><el-button link type="primary" @click="openTask(row.id)">填写 / 查看</el-button></template></el-table-column></el-table><el-empty v-if="!rows.length" description="本时间范围暂无任务，请先下发项目" /><p v-if="rows.length>=1000" class="muted">结果较多，仅显示前1000份任务，请缩小日期或门店范围。</p>
      </template></el-tab-pane>
    </el-tabs>
    <el-dialog v-model="editorOpen" fullscreen destroy-on-close :close-on-click-modal="false" :before-close="closeEditor" title="编辑表单">
      <StoreTaskFormDesigner v-if="editorOpen" ref="designerRef" :editor="editor" :templates="templates" :busy="busy" @edit="edit" @new="newProject" @save="save" />
    </el-dialog>
    <el-drawer v-model="dispatchOpen" size="min(780px,95vw)" title="下发设置 · 选择生效门店与周期" :close-on-click-modal="false"><section class="dispatch-panel"><h2>配置生效门店与执行日期</h2><el-form label-position="top"><el-form-item label="任务项目"><el-select v-model="dispatchForm.template_id" style="width:100%"><el-option v-for="t in templates" :key="t.id" :label="t.title" :value="t.id" /></el-select></el-form-item><el-form-item label="生效门店"><StoreRegionSelect v-model="dispatchForm.store_ids" :stores="config.stores" multiple restrict-to-stores input-width="100%" placeholder="选择门店或按区域勾选" /></el-form-item><el-form-item label="周期"><el-radio-group v-model="dispatchForm.frequency"><el-radio-button value="once">单次</el-radio-button><el-radio-button value="daily">每日</el-radio-button><el-radio-button value="weekly">每周</el-radio-button><el-radio-button value="monthly">每月</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="dispatchForm.frequency!=='once'" label="生效方式"><el-radio-group v-model="dispatchForm.long_term"><el-radio-button :value="true">长期生效</el-radio-button><el-radio-button :value="false">指定日期范围</el-radio-button></el-radio-group></el-form-item><el-form-item v-if="dispatchForm.long_term && dispatchForm.frequency!=='once'" label="开始日期"><el-date-picker v-model="dispatchRange[0]" type="date" value-format="YYYY-MM-DD" :clearable="false" /></el-form-item><el-form-item v-else label="生成日期范围（单次批量最多93天）"><el-date-picker v-model="dispatchRange" type="daterange" value-format="YYYY-MM-DD" :clearable="false" /></el-form-item><el-form-item label="每次截止时间（北京时间）"><el-time-select v-model="dispatchForm.due_time" start="00:00" end="23:30" step="00:30" /></el-form-item></el-form><p class="muted">长期计划无需结束日期，按北京时间每天自动生成当日任务，直到手动停用。每周以开始日星期为准，每月以开始日日期为准，短月取月末。表单沿用启用时版本；修改后请停用旧计划再重新下发。</p><el-button type="primary" :loading="busy" @click="publish">确认下发</el-button><el-alert v-if="dispatchResult" :title="dispatchResult" type="success" :closable="false" class="space" /></section>
    </el-drawer>
    <el-drawer v-model="plansOpen" size="min(900px,95vw)" title="长期计划管理"><h2 class="space">长期计划</h2><el-empty v-if="!plans.length" description="暂无长期计划" /><el-table v-else :data="plans"><el-table-column prop="title" label="项目" /><el-table-column prop="store_name" label="门店" /><el-table-column label="周期" width="75"><template #default="{row}">{{ {daily:'每日',weekly:'每周',monthly:'每月'}[row.frequency] }}</template></el-table-column><el-table-column prop="start_date" label="开始日期" width="115" /><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.active?'success':'info'">{{row.active?'长期生效':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="75"><template #default="{row}"><el-button v-if="row.active" link type="danger" :disabled="busy" @click="stopPlan(row)">停用</el-button></template></el-table-column></el-table></el-drawer>
    <el-drawer v-model="drawer" size="min(760px,95vw)" title="门店任务 · 共同执行" @closed="task=null">
      <template v-if="task"><header class="task-heading"><h2>{{ task.title }}</h2><p>{{ task.store_name }} · {{ task.business_date }}</p><el-tag :type="tone(task.status)">{{ status(task.status) }}</el-tag><span> 进行中 {{ task.total-task.completed }} · 已完成 {{ task.completed }} / {{ task.total }} 项</span><p>{{ task.description }}</p><p class="muted">门店成员看到相同进度 · 执行完成与审核状态分别记录 · 打开期间每5秒同步</p><el-button @click="reloadDetail(false)">刷新共同进度（保留未保存内容）</el-button></header>
        <el-alert v-if="task.status==='rejected'" :title="`审核退回：${task.submissions[0]?.review_note}`" type="warning" :closable="false" />
        <article v-for="(q,index) in task.results" :key="q.id" class="question-card"><h3><span v-if="q.required" class="required">*</span> {{ String(index+1).padStart(2,'0') }} {{ q.title }}</h3><StoreTaskInstructions :text="q.description" :images="q.guide_images||[]" /><el-tag size="small">{{q.execution_mode==='single'?'单人完成':'多人共同完成'}}</el-tag> <el-tag size="small" :type="q.conflict?'danger':q.complete?'success':'info'">{{ q.conflict?'结果不一致，请协调后修改':q.complete?'已填写':'待填写' }}</el-tag>
          <p v-if="q.owner" class="muted">{{q.complete?'实际完成人':'正在填写'}}：{{q.owner.name}} · 其他成员可查看</p><p v-else-if="q.complete" class="muted">实际完成人：{{(q.completed_by||[]).map(a=>a.name).join('、')}}</p>
          <div class="contribution" v-for="a in q.contributions" :key="a.id"><strong>{{ a.user_name }}</strong> <small>{{ fmt(a.created_at) }}</small><p v-if="a.response.value">{{ displayValue(q,a.response.value) }}</p><el-button v-for="image in a.response.images" :key="image" size="small" @click="showPhoto(image)">查看照片</el-button><span v-if="!a.response.value && !a.response.images.length" class="muted">已清空本人内容</span></div>
          <div v-if="canAnswer(q)" class="answer-form"><label>我的填写</label><template v-if="q.type==='photo'"><input type="file" accept="image/jpeg,image/png,image/webp" :disabled="busy" @change="upload(q,$event)" /><p>合计要求 {{ q.min }}—{{ q.max }} 张；我的待保存照片 {{ answers[q.id]?.images.length || 0 }} 张</p><div v-for="(image,i) in answers[q.id]?.images" :key="image"><el-button link @click="showPhoto(image)">照片{{ i+1 }}</el-button><el-button link type="danger" @click="answers[q.id].images.splice(i,1)">移除本人照片</el-button></div></template><el-select v-else-if="['choice','dropdown'].includes(q.type)" v-model="answers[q.id].value" clearable><el-option v-for="option in q.options" :key="option" :label="option" :value="option" /></el-select><el-select v-else-if="q.type==='multiple'" :model-value="multi(answers[q.id].value)" multiple @update:model-value="answers[q.id].value=JSON.stringify($event)"><el-option v-for="option in q.options" :key="option" :label="option" :value="option" /></el-select><el-date-picker v-else-if="q.type==='date'" v-model="answers[q.id].value" type="date" value-format="YYYY-MM-DD" placeholder="选择日期" /><el-input v-else v-model="answers[q.id].value" :type="q.type==='text'&&q.multiline!==false?'textarea':'text'" :maxlength="q.maxLength||2000" :placeholder="q.placeholder||'请输入'" :inputmode="q.type==='number'?'decimal':'text'" /><el-button type="primary" plain :loading="busy" @click="saveAnswer(q)">保存此项</el-button></div>
        </article>
        <el-button v-if="can('store-tasks.execute') && !['pending','approved'].includes(task.status)" type="primary" :loading="busy" @click="submit">提交整份任务审核</el-button>

        <h3>提交与审核历史</h3><el-collapse><el-collapse-item v-for="record in task.submissions" :key="record.id" :title="`第${record.version}版 · ${status(record.status)} · ${record.submitted_name} · ${fmt(record.submitted_at)}`" :name="record.id"><p>审核人：{{ record.reviewed_name || '待审核' }} · {{ record.review_note || '暂无意见' }}</p><div v-for="q in record.snapshot" :key="q.id"><strong>{{ q.title }}</strong><StoreTaskInstructions :text="q.description" :images="q.guide_images||[]" /><p v-for="a in q.contributions" :key="a.id">{{ a.user_name }}：{{ displayValue(q,a.response.value) }}<el-button v-for="image in a.response.images" :key="image" link @click="showPhoto(image)">查看历史照片</el-button></p></div></el-collapse-item></el-collapse>
      </template>
    </el-drawer>
    <el-dialog v-model="photoDialog" title="任务照片" width="min(700px,95vw)"><img v-if="photo" :src="photo" alt="成员提交的任务照片" style="width:100%;max-height:70vh;object-fit:contain" /></el-dialog>
  </main>
</template>
<script setup>
import { reactive, ref, onMounted, onBeforeUnmount, defineAsyncComponent } from 'vue'
import StoreTaskTemplateList from '@/components/StoreTaskTemplateList.vue'
import StoreRegionSelect from '@/components/StoreRegionSelect.vue'
import StoreTaskInstructions from '@/components/StoreTaskInstructions.vue'
import StoreTaskSubmissionReview from '@/components/StoreTaskSubmissionReview.vue'
const StoreTaskFormDesigner=defineAsyncComponent(()=>import('@/components/StoreTaskFormDesigner.vue'))
import { ElMessage, ElMessageBox } from 'element-plus'
import { storeTaskApi } from '@/api'
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const tab=ref('templates'), config=reactive({stores:[],permissions:[]}), templates=ref([]), editor=reactive({title:'',description:'',questions:[]}), rows=ref([]), range=ref([today(),today()]), storeId=ref(null), loading=ref(false), busy=ref(false), error=ref(''), dispatchResult=ref('')
const dispatchForm=reactive({template_id:null,store_ids:[],frequency:'daily',due_time:'10:00',long_term:true}), dispatchRange=ref([today(),today()]), plans=ref([])
const progressView=ref('submissions'),submissionView=ref(null)
const editorOpen=ref(false),dispatchOpen=ref(false),plansOpen=ref(false),designerRef=ref(null)
const drawer=ref(false), task=ref(null), answers=reactive({}), reviewNote=ref(''), photoDialog=ref(false), photo=ref('')
function multi(v){try{return JSON.parse(v||'[]')}catch{return []}}
function displayValue(q,v){return q.type==='multiple'?multi(v).join('、'):v}
const can=code=>config.permissions.includes('*')||config.permissions.includes(code)
const canAnswer=q=>can('store-tasks.execute')&&!['pending','approved'].includes(task.value?.status)&&(q.execution_mode!=='single'||!q.owner||q.owner.id===currentUserId)
let progressTimer,detailRequest=0
onBeforeUnmount(()=>clearInterval(progressTimer))
onMounted(()=>{progressTimer=setInterval(()=>{if(drawer.value&&task.value?.id&&!busy.value&&!document.hidden)reloadDetail(false,true)},5000)})
let currentUserId=0
const status=s=>({draft:'待提交',pending:'待审核',approved:'已通过',rejected:'已退回'}[s]||s), tone=s=>({pending:'warning',approved:'success',rejected:'danger'}[s]||'info')
const fmt=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—'
async function attempt(fn){busy.value=true;error.value='';try{await fn()}catch(e){if(e!=='cancel'&&e!=='close'){error.value=e.message||'操作失败';ElMessage.error(error.value)}}finally{busy.value=false}}
function edit(item){Object.keys(editor).forEach(k=>delete editor[k]);Object.assign(editor,JSON.parse(JSON.stringify(item)));editorOpen.value=true}
function newProject(draft){edit(draft?.questions ? draft : config.seed)}
async function closeEditor(done){if(busy.value)return;if(!designerRef.value||await designerRef.value.discard())done()}
function openDispatch(item){dispatchForm.template_id=item.id;dispatchForm.store_ids=[];dispatchForm.frequency='daily';dispatchForm.long_term=true;dispatchForm.due_time='10:00';dispatchRange.value=[today(),today()];dispatchResult.value='';dispatchOpen.value=true}
async function load(){loading.value=true;error.value='';try{Object.assign(config,await storeTaskApi.config());currentUserId=config.user_id; if(can('store-tasks.manage')){templates.value=(await storeTaskApi.templates()).templates;}else tab.value='progress';await loadRows();await loadPlans();await submissionView.value?.load()}catch(e){error.value=e.message}finally{loading.value=false}}
async function loadRows(){try{rows.value=(await storeTaskApi.list({from:range.value[0],to:range.value[1],store_id:storeId.value})).rows}catch(e){rows.value=[];error.value=e.message}}
async function save(){await attempt(async()=>{
  if(!editor.title?.trim())throw new Error('请填写项目名称')
  if(!editor.questions.length)throw new Error('请至少添加一个问题')
  for(const [i,q] of editor.questions.entries()){
    const n=String(i+1).padStart(2,'0')
    if(!q.title?.trim())throw new Error(`请填写第${n}题的问题标题`)
    if(q.type==='choice'){
      const options=(q.options || []).map(v=>v.trim()).filter(Boolean)
      if(options.length<2||new Set(options).size!==q.options.length)throw new Error(`第${n}题请设置至少两个不为空、不重复的选项`)
    }
    if(q.type==='photo'&&(q.min>q.max||q.min==null||q.max==null))throw new Error(`第${n}题请设置正确的图片数量`)
  }
  const {id}=await storeTaskApi.save(editor);templates.value=(await storeTaskApi.templates()).templates;edit(templates.value.find(t=>t.id===id));dispatchForm.template_id=id;ElMessage.success('项目已保存')
})}
async function publish(){await attempt(async()=>{if(!dispatchForm.template_id||!dispatchForm.store_ids.length)throw new Error('请选择项目和生效门店');const long=dispatchForm.long_term&&dispatchForm.frequency!=='once';await ElMessageBox.confirm(`向${dispatchForm.store_ids.length}家门店${long?'启用长期计划，直到手动停用':'下发指定日期范围的任务'}？`,'确认下发');const result=await storeTaskApi.dispatch({...dispatchForm,long_term:long,from:dispatchRange.value[0],to:dispatchRange.value[1]});dispatchResult.value=long?`已启用${result.schedules}家门店的长期计划，每天自动生成到期任务`:`新建${result.created}份任务，已有${result.existing}份保持不变`;range.value=long?[today(),today()]:[...dispatchRange.value];await loadRows();await loadPlans()})}
async function loadPlans(){if(can('store-tasks.manage'))plans.value=(await storeTaskApi.schedules()).rows}
async function stopPlan(plan){await attempt(async()=>{await ElMessageBox.confirm(`停用「${plan.store_name} · ${plan.title}」长期计划？已有任务和提交记录保留。`,'停用计划');await storeTaskApi.stopSchedule(plan.id);await loadPlans();ElMessage.success('长期计划已停用')})}
async function openTask(id){drawer.value=true;task.value={id,results:[],submissions:[]};Object.keys(answers).forEach(k=>delete answers[k]);await reloadDetail(true)}
async function reloadDetail(reset,quiet=false){const id=task.value?.id,request=++detailRequest;if(!id)return;try{const data=await storeTaskApi.detail(id);if(request!==detailRequest||!drawer.value||task.value?.id!==id)return;task.value=data.task;const listed=rows.value.find(r=>r.id===id);if(listed)Object.assign(listed,{completed:data.task.completed,total:data.task.total,in_progress:data.task.total-data.task.completed,status:data.task.status});for(const q of task.value.results){if(reset||!answers[q.id]){const own=q.contributions.find(a=>a.user_id===currentUserId);answers[q.id]=JSON.parse(JSON.stringify(own?.response||{value:'',images:[]}))}}}catch(e){if(!quiet)ElMessage.error(e.message)}}
async function upload(q,event){const file=event.target.files?.[0];event.target.value='';if(!file)return;await attempt(async()=>{if(file.size>4*1024*1024)throw new Error('照片最多4MB');if(answers[q.id].images.length>=q.max)throw new Error('已达到本人照片数量上限');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const result=await storeTaskApi.upload(task.value.id,data);answers[q.id].images.push(result.path)})}
async function saveAnswer(q){await attempt(async()=>{await storeTaskApi.answer(task.value.id,{question_id:q.id,revision:task.value.revision,...answers[q.id]});await reloadDetail(false);answers[q.id]=JSON.parse(JSON.stringify(task.value.results.find(r=>r.id===q.id).contributions.find(a=>a.user_id===currentUserId).response));ElMessage.success('已保存，其他成员可查看')})}
async function submit(){await attempt(async()=>{if(task.value.results.some(q=>canAnswer(q)&&JSON.stringify(answers[q.id])!==JSON.stringify(q.contributions.find(a=>a.user_id===currentUserId)?.response||{value:'',images:[]})))throw new Error('还有未保存的填写，请先保存各题内容');await ElMessageBox.confirm('请先保存各题内容。提交后本版冻结，等待审核。','提交审核');await storeTaskApi.submit(task.value.id,{revision:task.value.revision});await reloadDetail(false);await loadRows()})}
async function review(status){await attempt(async()=>{await storeTaskApi.review(task.value.id,{status,note:reviewNote.value,version:task.value.submissions[0].version});reviewNote.value='';await reloadDetail(false);await loadRows()})}
async function showPhoto(path){await attempt(async()=>{photo.value=(await storeTaskApi.photo(path)).data;photoDialog.value=true})}
onMounted(load)
</script>
<style scoped>
.store-tasks{padding:24px;max-width:1500px;margin:auto;color:var(--el-text-color-primary)}.page-header,.section-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.page-header h1{margin:4px 0;font-size:26px}.page-header p,.muted{color:var(--el-text-color-secondary);line-height:1.7}.eyebrow{font-size:12px;font-weight:600;color:var(--el-color-primary)!important}.template-layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:24px}.project-list,.editor-panel,.dispatch-panel{background:var(--el-bg-color);border:1px solid var(--el-border-color-light);border-radius:12px;padding:20px}.project-list button{display:flex;flex-direction:column;text-align:left;width:100%;padding:16px;margin-top:12px;background:var(--el-fill-color-light);border:1px solid transparent;border-radius:8px;cursor:pointer;gap:8px}.project-list button.selected{border-color:var(--el-color-primary)}.project-list span{font-size:12px;color:var(--el-text-color-secondary)}.editor-panel h2,.dispatch-panel h2{font-size:19px}.store-label{background:var(--el-color-primary-light-9);padding:16px;border-radius:8px;margin-bottom:18px}.question-card{padding:20px;border:1px solid var(--el-border-color-light);border-radius:10px;margin:14px 0;background:var(--el-bg-color)}.question-card h3{font-size:16px;margin:0 0 12px}.question-settings{display:grid;grid-template-columns:minmax(0,1fr) 140px 65px;gap:12px;margin:16px 0}.upload-placeholder{display:flex;align-items:center;justify-content:center;gap:8px;min-height:44px;background:var(--el-fill-color-light);margin:14px 0;border-radius:5px}.quantity{font-size:13px;display:flex;align-items:center;flex-wrap:wrap;gap:8px}.required{color:var(--el-color-danger)}.add-question{width:100%;min-height:44px}.dispatch-panel{max-width:720px}.space{margin:16px 0}.filters{display:flex;flex-wrap:wrap;gap:12px;margin:12px 0}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:20px 0}.metrics div{padding:18px;border:1px solid var(--el-border-color-light);border-radius:10px;display:flex;flex-direction:column;gap:8px}.metrics strong{font-size:26px}.contribution{background:var(--el-fill-color-light);padding:12px;margin:10px 0;border-radius:6px}.answer-form{border-top:1px dashed var(--el-border-color);padding-top:16px;display:flex;flex-direction:column;gap:12px}.review-panel{margin:24px 0;padding:20px;background:var(--el-color-primary-light-9);border-radius:10px}.review-panel button{margin-top:12px}.task-heading{line-height:1.7}@media(max-width:800px){.template-layout{grid-template-columns:1fr}.store-tasks{padding:12px}.section-head{flex-wrap:wrap}.question-settings{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}}
</style>
