<template>
  <main class="region-page">
    <section class="region-hero"><div><span class="eyebrow">STORE REGION DIRECTORY</span><h2>门店区域管理</h2><p>按区域树逐级展开；末级区域下直接展示门店。</p></div><div class="hero-metrics"><span><b>{{ regions.length }}</b> 个区域</span><span><b>{{ stores.length }}</b> 家门店</span></div></section>
    <section class="region-console">
      <aside class="tree-pane"><div class="tree-title"><div><b>区域组织</b><small>点击区域展开下级</small></div><el-button type="primary" plain size="small" @click="openEditor()">新建区域</el-button></div><el-input v-model="treeKeyword" clearable placeholder="搜索区域或门店" class="tree-search" /><el-tree ref="treeRef" :data="treeData" node-key="key" :filter-node-method="filterTree" :expand-on-click-node="false" default-expand-all highlight-current @node-click="handleTreeClick"><template #default="{ data }"><span :class="['tree-node', data.kind]"><i>{{ data.kind === 'store' ? '●' : '▾' }}</i><b>{{ data.name }}</b><small v-if="data.kind === 'region'">{{ data.store_count }} 家</small></span></template></el-tree><el-empty v-if="!treeData.length" description="暂未建立区域" :image-size="70" /></aside>
      <section class="table-pane"><header class="table-header"><div><span class="table-eyebrow">STORE LIST</span><h3>{{ currentTitle }}</h3><p>{{ currentHint }}</p></div><div class="header-actions"><el-button v-if="activeRegion" plain @click="openEditor(activeRegion)">编辑区域</el-button><el-button v-if="activeRegion" type="primary" plain @click="openEditor(null, activeRegion.id)">新建下级</el-button></div></header>
        <div class="table-filters"><el-input v-model="tableKeyword" clearable placeholder="搜索门店名称" /><el-select v-model="statusFilter" clearable placeholder="全部状态"><el-option label="正常营业" value="正常营业" /><el-option label="筹建中" value="筹建中" /><el-option label="已闭店" value="已闭店" /></el-select><span class="table-count">共 {{ filteredRows.length }} 家门店</span></div>
        <el-table :data="filteredRows" stripe class="store-table" height="calc(100vh - 350px)" min-height="390"><el-table-column type="index" label="序号" width="80" /><el-table-column prop="store_name" label="门店名称" min-width="240" show-overflow-tooltip /><el-table-column label="区域归属" min-width="210"><template #default="{ row }">{{ regionPathForStore(row.id) || '未分组' }}</template></el-table-column><el-table-column prop="province" label="省份" width="120"><template #default="{ row }">{{ row.province || '—' }}</template></el-table-column><el-table-column prop="city" label="城市" width="120"><template #default="{ row }">{{ row.city || '—' }}</template></el-table-column><el-table-column label="编辑" width="100" fixed="right" align="center"><template #default="{ row }"><el-button type="primary" link @click="openStoreGroupEditor(row)">编辑</el-button></template></el-table-column><template #empty><el-empty :description="activeRegion ? '该区域下暂无门店' : '暂无门店数据'" :image-size="100" /></template></el-table>
      </section>
    </section>
    <el-dialog v-model="editorVisible" :title="isCreating ? '新建区域' : '编辑区域'" width="min(600px, calc(100vw - 32px))" class="region-editor-dialog" destroy-on-close><p class="dialog-lead">区域按层级组织。门店只应纳入末级区域，上级区域会自动汇总下级门店。</p><div class="editor-form editor-form-stacked"><label><span>区域名称</span><el-input v-model="form.name" maxlength="40" placeholder="例如：广东省、深圳市、龙岗区" /></label><label><span>上级区域</span><el-select v-model="form.parent_id" clearable placeholder="不选择则为顶级区域"><el-option v-for="option in parentOptions" :key="option.id" :label="option.path" :value="option.id" /></el-select></label><label><span>排序</span><el-input-number v-model="form.sort_order" :min="0" :max="9999" controls-position="right" /></label></div><template #footer><el-button v-if="!isCreating" type="danger" text @click="removeRegion">删除区域</el-button><span class="dialog-spacer"></span><el-button @click="editorVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveRegion">保存</el-button></template></el-dialog>
    <el-dialog v-model="storeGroupEditorVisible" :title="`编辑门店分组 · ${editingStore?.store_name || ''}`" width="min(500px, calc(100vw - 32px))" class="store-group-dialog" destroy-on-close><p class="dialog-lead">选择门店所属的末级区域。保存后会自动移出原分组；留空则为未分组。</p><label class="group-editor-field"><span>所属末级区域</span><el-select v-model="editingStoreRegionId" clearable placeholder="未分组" class="group-editor-select"><el-option v-for="region in leafRegionOptions" :key="region.id" :label="region.path" :value="region.id" /></el-select></label><template #footer><el-button @click="storeGroupEditorVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveStoreGroup">保存分组</el-button></template></el-dialog>
  </main>
</template>

<script setup>
import { computed, nextTick, onMounted, reactive, ref, watch } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { createStoreRegion, deleteStoreRegion, getStoreRegions, getStores, setStoreRegionMembership, updateStoreRegion } from '@/api'
const stores = ref([]), regions = ref([]), activeRegionId = ref(null), activeStoreId = ref(null), treeKeyword = ref(''), tableKeyword = ref(''), statusFilter = ref(''), editorVisible = ref(false), storeGroupEditorVisible = ref(false), isCreating = ref(false), saving = ref(false), editingStore = ref(null), editingStoreRegionId = ref(null), treeRef = ref()
const form = reactive({ name: '', parent_id: null, sort_order: 0 })
const regionById = computed(() => new Map(regions.value.map(region => [region.id, region])))
const activeRegion = computed(() => regionById.value.get(activeRegionId.value) || null)
const isLeaf = computed(() => Boolean(activeRegion.value) && !regions.value.some(region => Number(region.parent_id || 0) === Number(activeRegion.value.id)))
function directChildren(id) { return regions.value.filter(region => Number(region.parent_id || 0) === Number(id || 0)) }
function leafStoreIds(regionId) { const children = directChildren(regionId); if (!children.length) return new Set((regionById.value.get(regionId)?.store_ids || []).map(Number)); return children.reduce((set, child) => { leafStoreIds(child.id).forEach(id => set.add(id)); return set }, new Set()) }
function regionNode(region) { const children = directChildren(region.id); const node = { key: `r-${region.id}`, id: region.id, name: region.name, kind: 'region', store_count: leafStoreIds(region.id).size, children: [] }; node.children = children.length ? children.map(regionNode) : stores.value.filter(store => (region.store_ids || []).map(Number).includes(Number(store.id))).map(store => ({ key: `s-${store.id}`, id: store.id, name: store.store_name, kind: 'store' })); return node }
const treeData = computed(() => directChildren(null).map(regionNode))
const scopedRows = computed(() => { if (activeStoreId.value) return stores.value.filter(store => Number(store.id) === Number(activeStoreId.value)); if (!activeRegion.value) return stores.value; const ids = leafStoreIds(activeRegion.value.id); return stores.value.filter(store => ids.has(Number(store.id))) })
const filteredRows = computed(() => scopedRows.value.filter(store => (!tableKeyword.value || store.store_name.includes(tableKeyword.value.trim())) && (!statusFilter.value || store.status === statusFilter.value)))
const currentTitle = computed(() => activeStoreId.value ? stores.value.find(store => Number(store.id) === Number(activeStoreId.value))?.store_name || '门店详情' : activeRegion.value ? `${activeRegion.value.name} · 门店列表` : '全部门店')
const currentHint = computed(() => activeStoreId.value ? '当前选中单个门店。' : activeRegion.value ? (isLeaf.value ? '这是末级区域，列表展示其直接纳入的门店。' : '列表汇总当前区域全部下级末级区域的门店。') : '请选择左侧区域，或直接在此查看全部门店。')
const breadcrumbs = computed(() => { const rows = []; let current = activeRegion.value; while (current) { rows.unshift(current); current = regionById.value.get(current.parent_id) || null }; return rows })
function flatWithPaths(list) { const out = []; const walk = (rows, prefix = '') => rows.forEach(row => { const path = prefix ? `${prefix} / ${row.name}` : row.name; out.push({ ...row, path }); walk(directChildren(row.id), path) }); walk(directChildren(null)); return out }
const parentOptions = computed(() => { if (!activeRegionId.value || isCreating.value) return flatWithPaths(regions.value); const blocked = new Set([activeRegionId.value]); const visit = id => directChildren(id).forEach(child => { blocked.add(child.id); visit(child.id) }); visit(activeRegionId.value); return flatWithPaths(regions.value).filter(region => !blocked.has(region.id)) })
const leafRegionOptions = computed(() => flatWithPaths(regions.value).filter(region => !directChildren(region.id).length))
function filterTree(value, data) { if (!value) return true; return data.name.includes(value) }
function handleTreeClick(data) { if (data.kind === 'store') { activeStoreId.value = data.id; return } activeStoreId.value = null; activeRegionId.value = data.id }
function regionPathForStore(storeId) { const leaf = regions.value.find(region => !directChildren(region.id).length && (region.store_ids || []).map(Number).includes(Number(storeId))); if (!leaf) return ''; const parts = []; let current = leaf; while (current) { parts.unshift(current.name); current = regionById.value.get(current.parent_id) || null }; return parts.join(' / ') }
function openEditor(region = null, parentId = null) { isCreating.value = !region; Object.assign(form, region ? { name: region.name, parent_id: region.parent_id || null, sort_order: Number(region.sort_order) || 0 } : { name: '', parent_id: parentId, sort_order: 0 }); editorVisible.value = true }
function openStoreGroupEditor(store) { const currentRegion = regions.value.find(region => !directChildren(region.id).length && (region.store_ids || []).map(Number).includes(Number(store.id))); editingStore.value = store; editingStoreRegionId.value = currentRegion?.id || null; storeGroupEditorVisible.value = true }
async function loadData() { const [storeData, regionData] = await Promise.all([getStores({ page: 1, page_size: 500 }), getStoreRegions()]); stores.value = storeData.stores || []; regions.value = regionData.regions || []; if (activeRegionId.value && !activeRegion.value) activeRegionId.value = null }
async function saveRegion() { if (!form.name.trim()) return ElMessage.warning('请填写区域名称'); saving.value = true; try { const creating = isCreating.value; const payload = { name: form.name.trim(), parent_id: form.parent_id, sort_order: form.sort_order || 0 }; const data = creating ? await createStoreRegion(payload) : await updateStoreRegion(activeRegionId.value, { ...payload, store_ids: activeRegion.value?.store_ids || [] }); regions.value = data.regions || []; if (creating) activeRegionId.value = data.id; editorVisible.value = false; ElMessage.success(creating ? '区域已创建' : '区域已保存') } catch (error) { ElMessage.error(error.message || '保存失败') } finally { saving.value = false } }
async function saveStoreGroup() { if (!editingStore.value) return; saving.value = true; try { const data = await setStoreRegionMembership(editingStore.value.id, editingStoreRegionId.value); regions.value = data.regions || []; storeGroupEditorVisible.value = false; ElMessage.success(editingStoreRegionId.value ? '门店分组已更新' : '已移出所有分组') } catch (error) { ElMessage.error(error.message || '分组保存失败') } finally { saving.value = false } }
async function removeRegion() { if (!activeRegion.value) return; try { await ElMessageBox.confirm('删除后，下级区域会保留并升为顶级区域。确定删除当前区域吗？', '删除区域', { type: 'warning' }) } catch { return }; const parentId = activeRegion.value.parent_id || null; try { const data = await deleteStoreRegion(activeRegion.value.id); regions.value = data.regions || []; activeRegionId.value = parentId; editorVisible.value = false; ElMessage.success('区域已删除') } catch (error) { ElMessage.error(error.message || '删除失败') } }
watch(treeKeyword, async value => { await nextTick(); treeRef.value?.filter(value) })
onMounted(() => loadData().catch(error => ElMessage.error(error.message || '区域数据加载失败')))
</script>

<style scoped>
.region-page { max-width: 1440px; margin: 0 auto; }
.region-hero { min-height: 118px; padding: 24px 30px; border-radius: 16px; display: flex; align-items: center; justify-content: space-between; gap: 24px; color: #fff; background: linear-gradient(120deg, #15386e, #2876c8 62%, #4ca8e9); }
.eyebrow, .table-eyebrow { display: block; color: #b7dbff; font-size: 11px; font-weight: 800; letter-spacing: 1.6px; }.region-hero h2 { margin: 6px 0; font-size: 25px; }.region-hero p { margin: 0; color: #d9ecff; font-size: 13px; }.hero-metrics { display: flex; gap: 12px; }.hero-metrics span { min-width: 88px; padding: 10px 13px; border: 1px solid rgba(255,255,255,.24); border-radius: 10px; background: rgba(255,255,255,.12); font-size: 12px; }.hero-metrics b { display: block; margin-bottom: 2px; font-size: 20px; }
.region-console { display: grid; grid-template-columns: 280px minmax(0, 1fr); min-height: 650px; margin-top: 16px; overflow: hidden; border: 1px solid #e3e9f1; border-radius: 12px; background: #fff; box-shadow: 0 8px 22px rgba(31,62,106,.06); }.tree-pane { padding: 14px 12px; border-right: 1px solid #e5eaf1; background: #fbfcfe; }.tree-title, .table-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 12px; }.tree-title b { display: block; color: #29456a; font-size: 16px; }.tree-title small { display: block; margin-top: 4px; color: #93a0b3; font-size: 12px; }.tree-search { margin: 16px 0 10px; }.tree-node { display: flex; align-items: center; gap: 7px; width: 100%; padding-right: 8px; color: #3a4e6c; }.tree-node i { color: #8fa0b5; font-size: 10px; font-style: normal; }.tree-node.store i { color: #62a4f7; }.tree-node b { overflow: hidden; font-size: 13px; font-weight: 550; text-overflow: ellipsis; white-space: nowrap; }.tree-node small { margin-left: auto; color: #85a1c4; font-size: 11px; }.tree-pane :deep(.el-tree) { background: transparent; }.tree-pane :deep(.el-tree-node__content) { height: 31px; border-radius: 4px; }.tree-pane :deep(.el-tree-node__content:hover), .tree-pane :deep(.is-current > .el-tree-node__content) { background: #edf5ff; }
.table-pane { min-width: 0; padding: 22px; }.table-header { padding-bottom: 17px; border-bottom: 1px solid #e8edf4; }.table-header h3 { margin: 5px 0; color: #263f63; font-size: 20px; }.table-header p { margin: 0; color: #8a98aa; font-size: 12px; }.table-eyebrow { color: #5b87d3; }.header-actions { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 8px; }.table-filters { display: flex; align-items: center; gap: 12px; padding: 16px 0; }.table-filters :deep(.el-input) { width: 240px; }.table-filters :deep(.el-select) { width: 150px; }.table-count { margin-left: auto; color: #8190a5; font-size: 13px; }.store-table { width: 100%; overflow: hidden; border: 1px solid #e5eaf1; border-radius: 8px; }
.dialog-lead { margin: 0; color: #8290a5; font-size: 13px; line-height: 1.7; }.editor-form { display: grid; grid-template-columns: 1fr 1fr 120px; gap: 14px; padding: 20px 0 4px; }.editor-form-stacked { grid-template-columns: 1fr; gap: 17px; padding-top: 24px; }.editor-form label, .group-editor-field { display: flex; flex-direction: column; gap: 7px; color: #5d6e87; font-size: 13px; font-weight: 650; }.editor-form-stacked label:last-child { width: 170px; }.dialog-spacer { display: inline-block; width: 120px; }.group-editor-field { margin-top: 23px; }.group-editor-select { width: 100%; }
@media (max-width: 920px) { .region-console { grid-template-columns: 230px minmax(0,1fr); } }
@media (max-width: 720px) { .region-hero { align-items: flex-start; flex-direction: column; }.region-console { grid-template-columns: 1fr; }.tree-pane { max-height: 300px; border-right: 0; border-bottom: 1px solid #e5eaf1; }.table-pane { padding: 16px; }.table-header, .table-filters { align-items: flex-start; flex-direction: column; }.table-filters :deep(.el-input), .table-filters :deep(.el-select) { width: 100%; }.table-count { margin-left: 0; }.editor-form { grid-template-columns: 1fr; }.editor-form label:last-child { grid-column: auto; } }
</style>
